In [1]:
%load_ext autoreload
%autoreload 2

# Import Libraries

In [2]:
#!pip install "numpy<1.24" --force-reinstall

In [3]:
#!pip install --force-reinstall catboost

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
import os

import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
import spacy
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.utils.class_weight import compute_class_weight
import catboost as cat
from catboost import Pool, CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import make_pipeline

import gensim.models
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# Read Data

In [6]:
#from google.colab import drive
#drive.mount('/content/drive')

In [7]:
#train_path = '/content/drive/My Drive/train.csv'
#test_path = '/content/drive/My Drive/test.csv'

In [20]:
nltk.download("stopwords")
nltk_stopwords = nltk.corpus.stopwords.words("russian")
print(f'NLTK ru stopwords size: {len(nltk_stopwords)}', end='\n\n')
' '.join(nltk_stopwords)

NLTK ru stopwords size: 151

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/vaa2804/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

'и в во не что он на я с со как а то все она так его но да ты к у же вы за бы по только ее мне было вот от меня еще нет о из ему теперь когда даже ну вдруг ли если уже или ни быть был него до вас нибудь опять уж вам ведь там потом себя ничего ей может они тут где есть надо ней для мы тебя их чем была сам чтоб без будто чего раз тоже себе под будет ж тогда кто этот того потому этого какой совсем ним здесь этом один почти мой тем чтобы нее сейчас были куда зачем всех никогда можно при наконец два об другой хоть после над больше тот через эти нас про всего них какая много разве три эту моя впрочем хорошо свою этой перед иногда лучше чуть том нельзя такой им более всегда конечно всю между'

In [21]:
train_path = '../../train.csv'
test_path = '../../test.csv'

In [4]:
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)
print(f"Number of rows and columns in the train data set: {train.shape}")
print(f"Number of rows and columns in the test data set: {test.shape}")
train.head()

Number of rows and columns in the train data set: (48665, 2)
Number of rows and columns in the test data set: (12167, 2)

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [5]:
train['rate'].value_counts()

rate
5    26069
4     9922
3     6126
1     4138
2     2410
Name: count, dtype: int64

In [22]:
le = LabelEncoder()

train.rate = le.fit_transform(train.rate)
train.head()

,rate,text,cleaned_text
0,3,Очень понравилось. Были в начале марта с соба...,очень понравиться были в начало март с собака ...
1,4,В целом магазин устраивает.\nАссортимент позво...,в целое магазин устраивать ассортимент позволя...
2,4,"Очень хорошо что открылась 5 ка, теперь не над...",очень хороший что открыться ка теперь не надо ...
3,2,Пятёрочка громко объявила о том как она заботи...,громко объявить о том как она заботиться о пен...
4,2,"Тесно, вечная сутолока, между рядами трудно ра...",тесно вечный сутолока между ряд трудный разойт...

In [26]:
nlp = spacy.load("ru_core_news_sm")
#stopwords = nlp.Defaults.stop_words
nlp.stopwords = nltk_stopwords[:100]

In [27]:
print(f'NLP ru stopwords size: {len(nlp.stopwords)}', end='\n\n')
' '.join(nlp.stopwords)

NLP ru stopwords size: 100

'и в во не что он на я с со как а то все она так его но да ты к у же вы за бы по только ее мне было вот от меня еще нет о из ему теперь когда даже ну вдруг ли если уже или ни быть был него до вас нибудь опять уж вам ведь там потом себя ничего ей может они тут где есть надо ней для мы тебя их чем была сам чтоб без будто чего раз тоже себе под будет ж тогда кто этот того потому этого какой совсем ним здесь этом один'

In [28]:
train['cleaned_text'] = train['text'].apply(
    lambda x: ' '.join(
        token.lemma_.lower() for token in nlp(x) if
        not token.is_stop
        and token.is_punct
        and not token.is_digit
        and not token.like_email
        and not token.like_num
        and not token.is_space
    )
)

In [29]:
train_vec = TfidfVectorizer(ngram_range = (1,1), max_features = 500)
train_bow = train_vec.fit_transform(train['cleaned_text'])

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(train_bow, train['rate'], shuffle = True, random_state=2025)

In [ ]:
classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes = classes, y = y_train)
class_weights=dict(zip(classes,weights))
class_weights

In [ ]:
model = CatBoostClassifier(loss_function='MultiClass',  learning_rate = 0.05, iterations = 1000, class_weights = class_weights,  early_stopping_rounds= 200,  random_seed=42)

In [ ]:
model.fit(X_train,y_train, eval_set=(X_test, y_test),verbose = False)

In [ ]:
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

In [ ]:
test['cleaned_text'] = test['text'].apply(
    lambda x: ' '.join(
        token.lemma_.lower() for token in nlp(x) if
        not token.is_stop
        and not token.is_punct
        and not token.is_digit
        and not token.like_email
        and not token.like_num
        and not token.is_space
    )
)

In [ ]:
test_vec = TfidfVectorizer(ngram_range = (1,1), max_features = 500)
test_bow = test_vec.fit_transform(test['cleaned_text'])
predictions = model.predict(test_bow)

In [ ]:
sample_submission_path = '../../sample_submission.csv'
submission = pd.read_csv(sample_submission_path)
submission["rate"] = le.inverse_transform(predictions)
submission.head()

In [ ]:
submission_path = '../../submission.csv'
submission.to_csv(submission_path, index=False)

In [16]:
x_array = train['cleaned_text'].to_numpy()
x_array=x_array.tolist()

In [24]:
model = gensim.models.Word2Vec(
    sentences=x_array,
    vector_size=256, # default = 100
    window=3, # default = 5
    min_count=3,
    sg=1, # Training algorithm: 1 for skip-gram; otherwise CBOW
    hs=0, #  If 1, hierarchical softmax will be used for model training. If 0, and negative is non-zero, negative sampling will be used.
    negative=2, # If > 0, negative sampling will be used, if set to 0, no negative sampling is used.
    epochs=25, # Number of iterations (epochs) over the corpus
    seed=2023,
)

In [18]:
def text_to_vector(text):
    vectors = [model.wv[word] for word in text if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

In [25]:
X = np.array([text_to_vector(text) for text in x_array])
X_train, X_test, y_train, y_test = train_test_split(X, train['rate'], shuffle = True, random_state=2025)

In [20]:
classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes = classes, y = y_train)
class_weights=dict(zip(classes,weights))
class_weights

{1: 2.324713375796178,
 2: 3.9975903614457833,
 3: 1.596937212863706,
 4: 0.9847025495750709,
 5: 0.3734192756292204}

In [27]:
model = CatBoostClassifier(loss_function='MultiClass',  learning_rate = 0.05, iterations = 1000, class_weights = class_weights,  early_stopping_rounds= 200,  random_seed=42)

In [28]:
model.fit(X_train,y_train, eval_set=(X_test, y_test),verbose = False)

In [29]:
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.26      0.52      0.34       998
           2       0.09      0.16      0.11       584
           3       0.23      0.25      0.24      1555
           4       0.30      0.27      0.28      2509
           5       0.76      0.60      0.67      6521

    accuracy                           0.46     12167
   macro avg       0.33      0.36      0.33     12167
weighted avg       0.52      0.46      0.48     12167

In [ ]:
params = {
    'depth': [4, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1],
    'iterations': [300, 500, 700],
    'l2_leaf_reg': [1, 3, 5]
}

In [ ]:
grid_search = GridSearchCV(model, params, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

print("Лучшие параметры:", grid_search.best_params_)

# Preparing the data and creating Catboost model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(train, train['rate'], shuffle = True, random_state=2025)

In [ ]:
X_train.head()

,rate,text,cleaned_text
38373,5,"Хороший выбор товаров, побольше, чем у соседне...",хороший выбор товар большой соседний малый про...
37650,5,"Хорошая пятёрочка, всегда всё на своих местах....",хороший место небольшой парковка
11122,3,Последнее время очень упал общий уровень магаз...,последний время упасть общий уровень магазин с...
1978,5,"Хороший магазин! Отличное местоположение, ассо...",хороший магазин отличный местоположение ассорт...
42401,5,Обожаю кофе в этом магазине,обожать кофе магазин

In [ ]:
X_train = X_train.drop(['rate','text'],axis = 1)
X_test = X_test.drop(['rate','text'],axis = 1)

In [ ]:
model = CatBoostClassifier( iterations = 1000, class_weights = class_weights,  early_stopping_rounds= 200, random_seed=42)

In [ ]:
model.fit(X_train, y_train, text_features=[0],verbose=False,eval_set=(X_test, y_test) )

In [ ]:
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.48      0.62      0.54       998
           2       0.17      0.24      0.20       584
           3       0.33      0.38      0.35      1555
           4       0.40      0.41      0.40      2509
           5       0.84      0.73      0.78      6521

    accuracy                           0.58     12167
   macro avg       0.44      0.48      0.45     12167
weighted avg       0.62      0.58      0.60     12167

Оптимизация гиперпараметров

In [ ]:
params = {
    'text_features' : [[0]],
    'depth': [4, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1],
    'iterations': [300, 500, 700],
    'l2_leaf_reg': [1, 3, 5]
}

In [ ]:
grid_search = GridSearchCV(model, params, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

print("Лучшие параметры:", grid_search.best_params_)

0:	learn: 1.6034776	total: 2.05s	remaining: 10m 12s
1:	learn: 1.5976230	total: 3.6s	remaining: 8m 56s
2:	learn: 1.5919506	total: 5.39s	remaining: 8m 53s
3:	learn: 1.5863597	total: 7.18s	remaining: 8m 51s
4:	learn: 1.5809381	total: 8.59s	remaining: 8m 26s
5:	learn: 1.5759222	total: 9.96s	remaining: 8m 7s
6:	learn: 1.5706248	total: 11.3s	remaining: 7m 54s
7:	learn: 1.5657839	total: 12.9s	remaining: 7m 52s
8:	learn: 1.5614700	total: 14.3s	remaining: 7m 41s
9:	learn: 1.5570528	total: 15.7s	remaining: 7m 35s
10:	learn: 1.5526024	total: 17s	remaining: 7m 25s
11:	learn: 1.5487421	total: 18s	remaining: 7m 13s
12:	learn: 1.5450480	total: 19.4s	remaining: 7m 8s
13:	learn: 1.5411329	total: 20.9s	remaining: 7m 6s
14:	learn: 1.5368641	total: 22.3s	remaining: 7m 3s
15:	learn: 1.5325636	total: 23.5s	remaining: 6m 57s
16:	learn: 1.5284162	total: 24.9s	remaining: 6m 54s
17:	learn: 1.5243719	total: 26.5s	remaining: 6m 55s
18:	learn: 1.5204316	total: 28s	remaining: 6m 53s
19:	learn: 1.5165897	total: 29.3s	remaining: 6m 50s
20:	learn: 1.5131911	total: 30.7s	remaining: 6m 47s
21:	learn: 1.5094673	total: 32s	remaining: 6m 44s
22:	learn: 1.5059277	total: 33.5s	remaining: 6m 43s
23:	learn: 1.5022603	total: 35.2s	remaining: 6m 44s
24:	learn: 1.4987287	total: 36.6s	remaining: 6m 42s
25:	learn: 1.4951033	total: 37.8s	remaining: 6m 38s
26:	learn: 1.4916779	total: 39.6s	remaining: 6m 40s
27:	learn: 1.4883256	total: 41s	remaining: 6m 38s
28:	learn: 1.4851119	total: 42.3s	remaining: 6m 35s
29:	learn: 1.4820475	total: 43.7s	remaining: 6m 33s
30:	learn: 1.4788305	total: 45.1s	remaining: 6m 31s
31:	learn: 1.4756940	total: 46.4s	remaining: 6m 28s
32:	learn: 1.4727323	total: 47.6s	remaining: 6m 25s
33:	learn: 1.4696669	total: 49s	remaining: 6m 23s
34:	learn: 1.4667177	total: 50.5s	remaining: 6m 22s
35:	learn: 1.4637940	total: 51.9s	remaining: 6m 20s
36:	learn: 1.4613050	total: 53.1s	remaining: 6m 17s
37:	learn: 1.4584679	total: 54.5s	remaining: 6m 16s
38:	learn: 1.4560648	total: 55.8s	remaining: 6m 13s
39:	learn: 1.4533037	total: 57.1s	remaining: 6m 10s
40:	learn: 1.4505688	total: 58.3s	remaining: 6m 8s
41:	learn: 1.4482807	total: 59.5s	remaining: 6m 5s
42:	learn: 1.4460465	total: 1m	remaining: 6m 2s
43:	learn: 1.4438171	total: 1m 2s	remaining: 6m
44:	learn: 1.4416245	total: 1m 3s	remaining: 5m 58s
45:	learn: 1.4389222	total: 1m 4s	remaining: 5m 56s
46:	learn: 1.4367295	total: 1m 5s	remaining: 5m 54s
47:	learn: 1.4344275	total: 1m 7s	remaining: 5m 52s
48:	learn: 1.4321410	total: 1m 8s	remaining: 5m 50s
49:	learn: 1.4299566	total: 1m 10s	remaining: 5m 50s
50:	learn: 1.4280222	total: 1m 11s	remaining: 5m 47s
51:	learn: 1.4260496	total: 1m 12s	remaining: 5m 45s
52:	learn: 1.4240148	total: 1m 13s	remaining: 5m 44s
53:	learn: 1.4221106	total: 1m 15s	remaining: 5m 41s
54:	learn: 1.4198885	total: 1m 16s	remaining: 5m 41s
55:	learn: 1.4179560	total: 1m 17s	remaining: 5m 39s
56:	learn: 1.4158547	total: 1m 19s	remaining: 5m 37s
57:	learn: 1.4141194	total: 1m 20s	remaining: 5m 35s
58:	learn: 1.4121872	total: 1m 21s	remaining: 5m 33s
59:	learn: 1.4100647	total: 1m 23s	remaining: 5m 32s
60:	learn: 1.4079992	total: 1m 24s	remaining: 5m 31s
61:	learn: 1.4058045	total: 1m 25s	remaining: 5m 30s
62:	learn: 1.4039342	total: 1m 27s	remaining: 5m 28s
63:	learn: 1.4020463	total: 1m 28s	remaining: 5m 26s
64:	learn: 1.4002825	total: 1m 30s	remaining: 5m 25s
65:	learn: 1.3983716	total: 1m 31s	remaining: 5m 24s
66:	learn: 1.3965428	total: 1m 32s	remaining: 5m 22s
67:	learn: 1.3947235	total: 1m 34s	remaining: 5m 22s
68:	learn: 1.3930126	total: 1m 35s	remaining: 5m 20s
69:	learn: 1.3913372	total: 1m 37s	remaining: 5m 19s
70:	learn: 1.3895990	total: 1m 38s	remaining: 5m 17s
71:	learn: 1.3881981	total: 1m 39s	remaining: 5m 15s
72:	learn: 1.3864773	total: 1m 41s	remaining: 5m 14s
73:	learn: 1.3847845	total: 1m 42s	remaining: 5m 12s
74:	learn: 1.3832312	total: 1m 43s	remaining: 5m 11s
75:	learn: 1.3817259	total: 1m 45s	remaining: 5m 9s
76:	learn: 1.3800658	total: 1m 46s	remaining: 5m 8s
77:	learn: 1.3787074	total: 1m 47s	remaining: 5m 6s
78:	learn: 1.3772151	total: 1m 49s	remaining: 5m 5s
79:	learn: 1.3757650	total: 1m 50s	remaining: 5m 3s
80:	learn: 1.3742019	total: 1m 51s	remaining: 5m 2s
81:	learn: 1.3729645	total: 1m 53s	remaining: 5m
82:	learn: 1.3714601	total: 1m 54s	remaining: 4m 59s
83:	learn: 1.3699954	total: 1m 56s	remaining: 4m 58s
84:	learn: 1.3687809	total: 1m 57s	remaining: 4m 56s
85:	learn: 1.3672981	total: 1m 58s	remaining: 4m 54s
86:	learn: 1.3657692	total: 1m 59s	remaining: 4m 53s
87:	learn: 1.3643682	total: 2m 1s	remaining: 4m 51s
88:	learn: 1.3630579	total: 2m 2s	remaining: 4m 50s
89:	learn: 1.3617366	total: 2m 3s	remaining: 4m 48s
90:	learn: 1.3603906	total: 2m 5s	remaining: 4m 47s
91:	learn: 1.3592078	total: 2m 6s	remaining: 4m 45s
92:	learn: 1.3579545	total: 2m 7s	remaining: 4m 44s
93:	learn: 1.3567433	total: 2m 9s	remaining: 4m 42s
94:	learn: 1.3555014	total: 2m 10s	remaining: 4m 41s
95:	learn: 1.3541938	total: 2m 11s	remaining: 4m 40s
96:	learn: 1.3530084	total: 2m 13s	remaining: 4m 38s
97:	learn: 1.3519905	total: 2m 14s	remaining: 4m 37s
98:	learn: 1.3510357	total: 2m 15s	remaining: 4m 35s
99:	learn: 1.3498987	total: 2m 17s	remaining: 4m 34s
100:	learn: 1.3487526	total: 2m 18s	remaining: 4m 32s
101:	learn: 1.3475935	total: 2m 19s	remaining: 4m 30s
102:	learn: 1.3463439	total: 2m 20s	remaining: 4m 29s
103:	learn: 1.3454289	total: 2m 22s	remaining: 4m 27s
104:	learn: 1.3442707	total: 2m 23s	remaining: 4m 26s
105:	learn: 1.3432870	total: 2m 25s	remaining: 4m 25s
106:	learn: 1.3423528	total: 2m 26s	remaining: 4m 23s
107:	learn: 1.3412747	total: 2m 27s	remaining: 4m 22s
108:	learn: 1.3404865	total: 2m 28s	remaining: 4m 20s
109:	learn: 1.3395365	total: 2m 29s	remaining: 4m 18s
110:	learn: 1.3387205	total: 2m 31s	remaining: 4m 17s
111:	learn: 1.3378694	total: 2m 32s	remaining: 4m 15s
112:	learn: 1.3368263	total: 2m 33s	remaining: 4m 14s
113:	learn: 1.3360618	total: 2m 34s	remaining: 4m 12s
114:	learn: 1.3350572	total: 2m 36s	remaining: 4m 11s
115:	learn: 1.3342964	total: 2m 37s	remaining: 4m 9s
116:	learn: 1.3335769	total: 2m 38s	remaining: 4m 8s
117:	learn: 1.3326761	total: 2m 39s	remaining: 4m 6s
118:	learn: 1.3317374	total: 2m 41s	remaining: 4m 5s
119:	learn: 1.3311029	total: 2m 42s	remaining: 4m 3s
120:	learn: 1.3302170	total: 2m 43s	remaining: 4m 2s
121:	learn: 1.3294193	total: 2m 45s	remaining: 4m
122:	learn: 1.3285357	total: 2m 46s	remaining: 3m 59s
123:	learn: 1.3277103	total: 2m 47s	remaining: 3m 58s
124:	learn: 1.3270891	total: 2m 48s	remaining: 3m 56s
125:	learn: 1.3261789	total: 2m 50s	remaining: 3m 54s
126:	learn: 1.3253915	total: 2m 51s	remaining: 3m 53s
127:	learn: 1.3246940	total: 2m 52s	remaining: 3m 52s
128:	learn: 1.3241713	total: 2m 53s	remaining: 3m 50s
129:	learn: 1.3234490	total: 2m 55s	remaining: 3m 48s
130:	learn: 1.3227944	total: 2m 56s	remaining: 3m 47s
131:	learn: 1.3219835	total: 2m 57s	remaining: 3m 46s
132:	learn: 1.3211717	total: 2m 58s	remaining: 3m 44s
133:	learn: 1.3204600	total: 3m	remaining: 3m 43s
134:	learn: 1.3197964	total: 3m 1s	remaining: 3m 41s
135:	learn: 1.3190886	total: 3m 2s	remaining: 3m 40s
136:	learn: 1.3184774	total: 3m 4s	remaining: 3m 38s
137:	learn: 1.3178100	total: 3m 5s	remaining: 3m 37s
138:	learn: 1.3171575	total: 3m 6s	remaining: 3m 35s
139:	learn: 1.3164420	total: 3m 7s	remaining: 3m 34s
140:	learn: 1.3159146	total: 3m 8s	remaining: 3m 32s
141:	learn: 1.3153627	total: 3m 10s	remaining: 3m 31s
142:	learn: 1.3146904	total: 3m 11s	remaining: 3m 29s
143:	learn: 1.3140569	total: 3m 12s	remaining: 3m 28s
144:	learn: 1.3135118	total: 3m 14s	remaining: 3m 27s
145:	learn: 1.3129545	total: 3m 15s	remaining: 3m 26s
146:	learn: 1.3122877	total: 3m 16s	remaining: 3m 24s
147:	learn: 1.3117403	total: 3m 17s	remaining: 3m 23s
148:	learn: 1.3112199	total: 3m 19s	remaining: 3m 21s
149:	learn: 1.3107060	total: 3m 20s	remaining: 3m 20s
150:	learn: 1.3100924	total: 3m 21s	remaining: 3m 18s
151:	learn: 1.3095087	total: 3m 22s	remaining: 3m 17s
152:	learn: 1.3088405	total: 3m 24s	remaining: 3m 16s
153:	learn: 1.3083662	total: 3m 25s	remaining: 3m 14s
154:	learn: 1.3078405	total: 3m 26s	remaining: 3m 13s
155:	learn: 1.3074315	total: 3m 27s	remaining: 3m 11s
0:	learn: 1.6033469	total: 2.21s	remaining: 11m
1:	learn: 1.5974370	total: 3.77s	remaining: 9m 22s
2:	learn: 1.5917125	total: 5.29s	remaining: 8m 44s
3:	learn: 1.5861982	total: 7.18s	remaining: 8m 51s
4:	learn: 1.5804040	total: 8.75s	remaining: 8m 36s
5:	learn: 1.5751836	total: 9.96s	remaining: 8m 8s
6:	learn: 1.5700737	total: 11.4s	remaining: 7m 56s
7:	learn: 1.5651882	total: 12.8s	remaining: 7m 48s
8:	learn: 1.5602466	total: 14.4s	remaining: 7m 44s
9:	learn: 1.5556227	total: 15.8s	remaining: 7m 38s
10:	learn: 1.5512698	total: 17.1s	remaining: 7m 29s
11:	learn: 1.5472487	total: 18.5s	remaining: 7m 23s
12:	learn: 1.5432303	total: 19.8s	remaining: 7m 16s
13:	learn: 1.5388039	total: 21.3s	remaining: 7m 15s
14:	learn: 1.5345304	total: 22.5s	remaining: 7m 8s
15:	learn: 1.5302203	total: 23.9s	remaining: 7m 5s
16:	learn: 1.5260494	total: 25.4s	remaining: 7m 2s
17:	learn: 1.5219777	total: 26.8s	remaining: 6m 59s
18:	learn: 1.5179212	total: 28.3s	remaining: 6m 58s
19:	learn: 1.5139932	total: 29.6s	remaining: 6m 54s
20:	learn: 1.5101801	total: 31s	remaining: 6m 51s
21:	learn: 1.5068550	total: 32.2s	remaining: 6m 47s
22:	learn: 1.5031551	total: 33.7s	remaining: 6m 45s
23:	learn: 1.4994044	total: 35.1s	remaining: 6m 43s
24:	learn: 1.4959066	total: 36.5s	remaining: 6m 41s
25:	learn: 1.4922225	total: 38.1s	remaining: 6m 41s
26:	learn: 1.4893001	total: 39.2s	remaining: 6m 36s
27:	learn: 1.4858740	total: 40.6s	remaining: 6m 34s
28:	learn: 1.4825291	total: 42s	remaining: 6m 32s
29:	learn: 1.4793814	total: 43.3s	remaining: 6m 30s
30:	learn: 1.4761205	total: 44.7s	remaining: 6m 27s
31:	learn: 1.4730402	total: 46s	remaining: 6m 25s
32:	learn: 1.4698204	total: 47.4s	remaining: 6m 23s
33:	learn: 1.4668119	total: 48.9s	remaining: 6m 22s
34:	learn: 1.4638158	total: 50.3s	remaining: 6m 20s
35:	learn: 1.4608674	total: 51.7s	remaining: 6m 19s
36:	learn: 1.4581157	total: 53s	remaining: 6m 16s
37:	learn: 1.4552502	total: 54.4s	remaining: 6m 14s
38:	learn: 1.4528493	total: 55.8s	remaining: 6m 13s
39:	learn: 1.4504885	total: 57s	remaining: 6m 10s
40:	learn: 1.4477671	total: 58.2s	remaining: 6m 7s
41:	learn: 1.4452097	total: 59.7s	remaining: 6m 6s
42:	learn: 1.4428994	total: 1m 1s	remaining: 6m 5s
43:	learn: 1.4404161	total: 1m 2s	remaining: 6m 3s
44:	learn: 1.4379440	total: 1m 3s	remaining: 6m 2s
45:	learn: 1.4354432	total: 1m 5s	remaining: 5m 59s
46:	learn: 1.4332232	total: 1m 6s	remaining: 5m 57s
47:	learn: 1.4309403	total: 1m 7s	remaining: 5m 55s
48:	learn: 1.4282251	total: 1m 9s	remaining: 5m 53s
49:	learn: 1.4258047	total: 1m 10s	remaining: 5m 51s
50:	learn: 1.4238544	total: 1m 11s	remaining: 5m 49s
51:	learn: 1.4219147	total: 1m 12s	remaining: 5m 47s
52:	learn: 1.4195734	total: 1m 14s	remaining: 5m 47s
53:	learn: 1.4176739	total: 1m 15s	remaining: 5m 45s
54:	learn: 1.4154308	total: 1m 17s	remaining: 5m 43s
55:	learn: 1.4133994	total: 1m 18s	remaining: 5m 42s
56:	learn: 1.4115319	total: 1m 20s	remaining: 5m 41s
57:	learn: 1.4097954	total: 1m 21s	remaining: 5m 39s
58:	learn: 1.4077460	total: 1m 22s	remaining: 5m 37s
59:	learn: 1.4056646	total: 1m 23s	remaining: 5m 35s
60:	learn: 1.4036201	total: 1m 25s	remaining: 5m 34s
61:	learn: 1.4015711	total: 1m 26s	remaining: 5m 32s
62:	learn: 1.3996902	total: 1m 28s	remaining: 5m 31s
63:	learn: 1.3975899	total: 1m 29s	remaining: 5m 30s
64:	learn: 1.3955294	total: 1m 30s	remaining: 5m 28s
65:	learn: 1.3936283	total: 1m 32s	remaining: 5m 27s
66:	learn: 1.3920444	total: 1m 33s	remaining: 5m 25s
67:	learn: 1.3900746	total: 1m 34s	remaining: 5m 23s
68:	learn: 1.3882142	total: 1m 36s	remaining: 5m 21s
69:	learn: 1.3864084	total: 1m 37s	remaining: 5m 20s
70:	learn: 1.3846508	total: 1m 38s	remaining: 5m 18s
71:	learn: 1.3831192	total: 1m 40s	remaining: 5m 17s
72:	learn: 1.3814985	total: 1m 41s	remaining: 5m 15s
73:	learn: 1.3799316	total: 1m 42s	remaining: 5m 14s
74:	learn: 1.3783595	total: 1m 44s	remaining: 5m 12s
75:	learn: 1.3768210	total: 1m 45s	remaining: 5m 10s
76:	learn: 1.3751834	total: 1m 46s	remaining: 5m 8s
77:	learn: 1.3739079	total: 1m 47s	remaining: 5m 7s
78:	learn: 1.3722757	total: 1m 49s	remaining: 5m 5s
79:	learn: 1.3707909	total: 1m 50s	remaining: 5m 4s
80:	learn: 1.3694017	total: 1m 52s	remaining: 5m 2s
81:	learn: 1.3681173	total: 1m 53s	remaining: 5m 1s
82:	learn: 1.3669105	total: 1m 54s	remaining: 4m 59s
83:	learn: 1.3655008	total: 1m 55s	remaining: 4m 57s
84:	learn: 1.3643513	total: 1m 57s	remaining: 4m 56s
85:	learn: 1.3629487	total: 1m 58s	remaining: 4m 54s
86:	learn: 1.3615500	total: 1m 59s	remaining: 4m 52s
87:	learn: 1.3601468	total: 2m	remaining: 4m 51s
88:	learn: 1.3588412	total: 2m 2s	remaining: 4m 49s
89:	learn: 1.3576733	total: 2m 3s	remaining: 4m 48s
90:	learn: 1.3563082	total: 2m 4s	remaining: 4m 46s
91:	learn: 1.3550009	total: 2m 6s	remaining: 4m 45s
92:	learn: 1.3539092	total: 2m 7s	remaining: 4m 43s
93:	learn: 1.3526732	total: 2m 8s	remaining: 4m 42s
94:	learn: 1.3517210	total: 2m 9s	remaining: 4m 40s
95:	learn: 1.3505189	total: 2m 11s	remaining: 4m 39s
96:	learn: 1.3492608	total: 2m 12s	remaining: 4m 37s
97:	learn: 1.3482270	total: 2m 13s	remaining: 4m 36s
98:	learn: 1.3471103	total: 2m 15s	remaining: 4m 34s
99:	learn: 1.3461333	total: 2m 16s	remaining: 4m 33s
100:	learn: 1.3447887	total: 2m 17s	remaining: 4m 31s
101:	learn: 1.3437527	total: 2m 19s	remaining: 4m 30s
102:	learn: 1.3424301	total: 2m 20s	remaining: 4m 28s
103:	learn: 1.3414929	total: 2m 21s	remaining: 4m 27s
104:	learn: 1.3402518	total: 2m 23s	remaining: 4m 25s
105:	learn: 1.3390497	total: 2m 24s	remaining: 4m 24s
106:	learn: 1.3380807	total: 2m 25s	remaining: 4m 23s
107:	learn: 1.3368377	total: 2m 27s	remaining: 4m 21s
108:	learn: 1.3357621	total: 2m 28s	remaining: 4m 20s
109:	learn: 1.3346550	total: 2m 29s	remaining: 4m 18s
110:	learn: 1.3336657	total: 2m 31s	remaining: 4m 17s
111:	learn: 1.3327786	total: 2m 32s	remaining: 4m 15s
112:	learn: 1.3318366	total: 2m 33s	remaining: 4m 14s
113:	learn: 1.3310737	total: 2m 35s	remaining: 4m 13s
114:	learn: 1.3300614	total: 2m 36s	remaining: 4m 11s
115:	learn: 1.3291908	total: 2m 37s	remaining: 4m 10s
116:	learn: 1.3285260	total: 2m 38s	remaining: 4m 8s
117:	learn: 1.3275850	total: 2m 40s	remaining: 4m 7s
118:	learn: 1.3266030	total: 2m 41s	remaining: 4m 5s
119:	learn: 1.3256316	total: 2m 42s	remaining: 4m 4s
120:	learn: 1.3248755	total: 2m 43s	remaining: 4m 2s
121:	learn: 1.3240643	total: 2m 45s	remaining: 4m 1s
122:	learn: 1.3232770	total: 2m 46s	remaining: 3m 59s
123:	learn: 1.3225306	total: 2m 47s	remaining: 3m 58s
124:	learn: 1.3217920	total: 2m 49s	remaining: 3m 56s
125:	learn: 1.3209627	total: 2m 50s	remaining: 3m 55s
126:	learn: 1.3200865	total: 2m 51s	remaining: 3m 53s
127:	learn: 1.3192325	total: 2m 53s	remaining: 3m 52s
128:	learn: 1.3185158	total: 2m 54s	remaining: 3m 51s
129:	learn: 1.3177794	total: 2m 55s	remaining: 3m 49s
130:	learn: 1.3169369	total: 2m 56s	remaining: 3m 48s
131:	learn: 1.3161230	total: 2m 58s	remaining: 3m 46s
132:	learn: 1.3152562	total: 2m 59s	remaining: 3m 45s
133:	learn: 1.3146556	total: 3m	remaining: 3m 43s
134:	learn: 1.3140128	total: 3m 1s	remaining: 3m 42s
135:	learn: 1.3133069	total: 3m 3s	remaining: 3m 40s
136:	learn: 1.3126329	total: 3m 4s	remaining: 3m 39s
137:	learn: 1.3118790	total: 3m 5s	remaining: 3m 37s
138:	learn: 1.3111057	total: 3m 6s	remaining: 3m 36s
139:	learn: 1.3105110	total: 3m 7s	remaining: 3m 34s
140:	learn: 1.3097809	total: 3m 9s	remaining: 3m 33s
141:	learn: 1.3092908	total: 3m 10s	remaining: 3m 31s
142:	learn: 1.3086471	total: 3m 11s	remaining: 3m 30s
143:	learn: 1.3079868	total: 3m 13s	remaining: 3m 29s
144:	learn: 1.3074514	total: 3m 14s	remaining: 3m 27s
145:	learn: 1.3069070	total: 3m 15s	remaining: 3m 26s
146:	learn: 1.3063380	total: 3m 16s	remaining: 3m 24s
147:	learn: 1.3057334	total: 3m 18s	remaining: 3m 23s
148:	learn: 1.3052833	total: 3m 19s	remaining: 3m 21s
149:	learn: 1.3047006	total: 3m 20s	remaining: 3m 20s
150:	learn: 1.3041796	total: 3m 21s	remaining: 3m 19s
151:	learn: 1.3036027	total: 3m 23s	remaining: 3m 17s
152:	learn: 1.3029615	total: 3m 24s	remaining: 3m 16s
153:	learn: 1.3024941	total: 3m 25s	remaining: 3m 14s
154:	learn: 1.3019345	total: 3m 26s	remaining: 3m 13s
155:	learn: 1.3012934	total: 3m 28s	remaining: 3m 12s
156:	learn: 1.3069609	total: 3m 29s	remaining: 3m 10s
157:	learn: 1.3065035	total: 3m 30s	remaining: 3m 9s
158:	learn: 1.3059900	total: 3m 31s	remaining: 3m 7s
159:	learn: 1.3055213	total: 3m 33s	remaining: 3m 6s
160:	learn: 1.3051149	total: 3m 34s	remaining: 3m 5s
161:	learn: 1.3045628	total: 3m 35s	remaining: 3m 3s
162:	learn: 1.3041192	total: 3m 37s	remaining: 3m 2s
163:	learn: 1.3036198	total: 3m 38s	remaining: 3m 1s
164:	learn: 1.3030692	total: 3m 39s	remaining: 2m 59s
165:	learn: 1.3026122	total: 3m 41s	remaining: 2m 58s
166:	learn: 1.3021027	total: 3m 42s	remaining: 2m 57s
167:	learn: 1.3016675	total: 3m 43s	remaining: 2m 55s
168:	learn: 1.3011654	total: 3m 44s	remaining: 2m 54s
169:	learn: 1.3006900	total: 3m 46s	remaining: 2m 52s
170:	learn: 1.3002198	total: 3m 47s	remaining: 2m 51s
171:	learn: 1.2997654	total: 3m 48s	remaining: 2m 50s
172:	learn: 1.2992538	total: 3m 49s	remaining: 2m 48s
173:	learn: 1.2989733	total: 3m 51s	remaining: 2m 47s
174:	learn: 1.2985988	total: 3m 52s	remaining: 2m 45s
175:	learn: 1.2980828	total: 3m 53s	remaining: 2m 44s
176:	learn: 1.2976206	total: 3m 55s	remaining: 2m 43s
177:	learn: 1.2972258	total: 3m 56s	remaining: 2m 41s
178:	learn: 1.2967114	total: 3m 57s	remaining: 2m 40s
179:	learn: 1.2964123	total: 3m 58s	remaining: 2m 39s
180:	learn: 1.2959511	total: 4m	remaining: 2m 37s
181:	learn: 1.2954851	total: 4m 1s	remaining: 2m 36s
182:	learn: 1.2951141	total: 4m 2s	remaining: 2m 35s
183:	learn: 1.2946955	total: 4m 3s	remaining: 2m 33s
184:	learn: 1.2943375	total: 4m 5s	remaining: 2m 32s
185:	learn: 1.2940336	total: 4m 7s	remaining: 2m 31s
186:	learn: 1.2936713	total: 4m 8s	remaining: 2m 30s
187:	learn: 1.2932543	total: 4m 9s	remaining: 2m 28s
188:	learn: 1.2929128	total: 4m 10s	remaining: 2m 27s
189:	learn: 1.2927021	total: 4m 12s	remaining: 2m 25s
190:	learn: 1.2922479	total: 4m 13s	remaining: 2m 24s
191:	learn: 1.2919345	total: 4m 15s	remaining: 2m 23s
192:	learn: 1.2915781	total: 4m 16s	remaining: 2m 22s
193:	learn: 1.2912723	total: 4m 17s	remaining: 2m 20s
194:	learn: 1.2908859	total: 4m 19s	remaining: 2m 19s
195:	learn: 1.2906409	total: 4m 20s	remaining: 2m 18s
196:	learn: 1.2902445	total: 4m 21s	remaining: 2m 16s
197:	learn: 1.2898503	total: 4m 22s	remaining: 2m 15s
198:	learn: 1.2894726	total: 4m 24s	remaining: 2m 14s
199:	learn: 1.2891503	total: 4m 25s	remaining: 2m 12s
200:	learn: 1.2888014	total: 4m 26s	remaining: 2m 11s
201:	learn: 1.2885034	total: 4m 27s	remaining: 2m 10s
202:	learn: 1.2882490	total: 4m 29s	remaining: 2m 8s
203:	learn: 1.2880233	total: 4m 30s	remaining: 2m 7s
204:	learn: 1.2877323	total: 4m 31s	remaining: 2m 5s
205:	learn: 1.2875483	total: 4m 32s	remaining: 2m 4s
206:	learn: 1.2872019	total: 4m 34s	remaining: 2m 3s
207:	learn: 1.2868628	total: 4m 35s	remaining: 2m 1s
208:	learn: 1.2865841	total: 4m 36s	remaining: 2m
209:	learn: 1.2863177	total: 4m 37s	remaining: 1m 59s
210:	learn: 1.2860206	total: 4m 39s	remaining: 1m 57s
211:	learn: 1.2857710	total: 4m 40s	remaining: 1m 56s
212:	learn: 1.2854511	total: 4m 42s	remaining: 1m 55s
213:	learn: 1.2851299	total: 4m 43s	remaining: 1m 53s
214:	learn: 1.2848322	total: 4m 44s	remaining: 1m 52s
215:	learn: 1.2844980	total: 4m 45s	remaining: 1m 51s
216:	learn: 1.2841432	total: 4m 47s	remaining: 1m 49s
217:	learn: 1.2838303	total: 4m 48s	remaining: 1m 48s
218:	learn: 1.2836088	total: 4m 49s	remaining: 1m 47s
219:	learn: 1.2833944	total: 4m 50s	remaining: 1m 45s
220:	learn: 1.2831077	total: 4m 52s	remaining: 1m 44s
221:	learn: 1.2829211	total: 4m 53s	remaining: 1m 43s
222:	learn: 1.2827841	total: 4m 54s	remaining: 1m 41s

In [ ]:
X_train = train["cleaned_text"]
y_train = train["rate"]

X_test = test["text"]


model = CatBoostClassifier(
    iterations=100,
    depth=5,
    random_seed=42
)

model.fit(
    X_train,
    y_train,
    text_features=[0],
    verbose=True
)

Learning rate set to 0.5
0:	learn: 1.1115052	total: 1.53s	remaining: 2m 31s
1:	learn: 1.0314105	total: 3.12s	remaining: 2m 33s
2:	learn: 0.9927610	total: 4.69s	remaining: 2m 31s
3:	learn: 0.9725062	total: 6.7s	remaining: 2m 40s
4:	learn: 0.9606198	total: 8.01s	remaining: 2m 32s
5:	learn: 0.9549722	total: 9.28s	remaining: 2m 25s
6:	learn: 0.9518823	total: 10.4s	remaining: 2m 18s
7:	learn: 0.9487206	total: 11.6s	remaining: 2m 13s
8:	learn: 0.9447613	total: 12.9s	remaining: 2m 10s
9:	learn: 0.9433536	total: 13.9s	remaining: 2m 5s
10:	learn: 0.9420060	total: 15.1s	remaining: 2m 2s
11:	learn: 0.9391503	total: 16.4s	remaining: 2m
12:	learn: 0.9360403	total: 17.9s	remaining: 1m 59s
13:	learn: 0.9351435	total: 18.9s	remaining: 1m 55s
14:	learn: 0.9339834	total: 20.1s	remaining: 1m 53s
15:	learn: 0.9328480	total: 21.1s	remaining: 1m 50s
16:	learn: 0.9301511	total: 22.4s	remaining: 1m 49s
17:	learn: 0.9295311	total: 23.5s	remaining: 1m 47s
18:	learn: 0.9286594	total: 24.7s	remaining: 1m 45s
19:	learn: 0.9248269	total: 26.4s	remaining: 1m 45s
20:	learn: 0.9234183	total: 27.9s	remaining: 1m 44s
21:	learn: 0.9217471	total: 29.1s	remaining: 1m 43s
22:	learn: 0.9208762	total: 30.5s	remaining: 1m 42s
23:	learn: 0.9193357	total: 31.9s	remaining: 1m 41s
24:	learn: 0.9177676	total: 33.3s	remaining: 1m 39s
25:	learn: 0.9168084	total: 35.2s	remaining: 1m 40s
26:	learn: 0.9159019	total: 36.3s	remaining: 1m 38s
27:	learn: 0.9148582	total: 38s	remaining: 1m 37s
28:	learn: 0.9129971	total: 39.4s	remaining: 1m 36s
29:	learn: 0.9122006	total: 40.6s	remaining: 1m 34s
30:	learn: 0.9113228	total: 41.9s	remaining: 1m 33s
31:	learn: 0.9102339	total: 43.3s	remaining: 1m 32s
32:	learn: 0.9095903	total: 44.6s	remaining: 1m 30s
33:	learn: 0.9084979	total: 46.1s	remaining: 1m 29s
34:	learn: 0.9077770	total: 47.2s	remaining: 1m 27s
35:	learn: 0.9067700	total: 48.4s	remaining: 1m 26s
36:	learn: 0.9054500	total: 49.5s	remaining: 1m 24s
37:	learn: 0.9042303	total: 50.8s	remaining: 1m 22s
38:	learn: 0.9034929	total: 52.6s	remaining: 1m 22s
39:	learn: 0.9027992	total: 53.8s	remaining: 1m 20s
40:	learn: 0.9023732	total: 54.9s	remaining: 1m 18s
41:	learn: 0.9008919	total: 56.3s	remaining: 1m 17s
42:	learn: 0.8998616	total: 57.6s	remaining: 1m 16s
43:	learn: 0.8986538	total: 58.9s	remaining: 1m 14s
44:	learn: 0.8981111	total: 60s	remaining: 1m 13s
45:	learn: 0.8975999	total: 1m 1s	remaining: 1m 11s
46:	learn: 0.8969456	total: 1m 2s	remaining: 1m 10s
47:	learn: 0.8964682	total: 1m 3s	remaining: 1m 8s
48:	learn: 0.8958153	total: 1m 4s	remaining: 1m 7s
49:	learn: 0.8953980	total: 1m 6s	remaining: 1m 6s
50:	learn: 0.8946945	total: 1m 7s	remaining: 1m 5s
51:	learn: 0.8937706	total: 1m 9s	remaining: 1m 3s
52:	learn: 0.8931477	total: 1m 10s	remaining: 1m 2s
53:	learn: 0.8926138	total: 1m 11s	remaining: 1m 1s
54:	learn: 0.8918910	total: 1m 13s	remaining: 59.7s
55:	learn: 0.8914177	total: 1m 14s	remaining: 58.4s
56:	learn: 0.8908602	total: 1m 15s	remaining: 56.9s
57:	learn: 0.8902957	total: 1m 16s	remaining: 55.4s
58:	learn: 0.8895564	total: 1m 17s	remaining: 54.1s
59:	learn: 0.8890678	total: 1m 18s	remaining: 52.6s
60:	learn: 0.8886634	total: 1m 20s	remaining: 51.2s
61:	learn: 0.8883236	total: 1m 21s	remaining: 49.9s
62:	learn: 0.8874236	total: 1m 22s	remaining: 48.6s
63:	learn: 0.8869081	total: 1m 23s	remaining: 47.1s
64:	learn: 0.8867450	total: 1m 25s	remaining: 45.8s
65:	learn: 0.8861652	total: 1m 26s	remaining: 44.4s
66:	learn: 0.8857064	total: 1m 27s	remaining: 42.9s
67:	learn: 0.8852322	total: 1m 28s	remaining: 41.7s
68:	learn: 0.8847331	total: 1m 29s	remaining: 40.4s
69:	learn: 0.8842047	total: 1m 31s	remaining: 39.2s
70:	learn: 0.8837931	total: 1m 32s	remaining: 37.8s
71:	learn: 0.8835689	total: 1m 33s	remaining: 36.5s
72:	learn: 0.8833572	total: 1m 34s	remaining: 35.1s
73:	learn: 0.8829977	total: 1m 35s	remaining: 33.7s
74:	learn: 0.8826296	total: 1m 37s	remaining: 32.4s
75:	learn: 0.8821048	total: 1m 38s	remaining: 31.1s
76:	learn: 0.8817200	total: 1m 39s	remaining: 29.7s
77:	learn: 0.8812353	total: 1m 40s	remaining: 28.4s
78:	learn: 0.8808862	total: 1m 41s	remaining: 27.1s
79:	learn: 0.8803223	total: 1m 43s	remaining: 25.8s
80:	learn: 0.8799902	total: 1m 44s	remaining: 24.4s
81:	learn: 0.8793501	total: 1m 45s	remaining: 23.2s
82:	learn: 0.8790330	total: 1m 47s	remaining: 22s
83:	learn: 0.8786015	total: 1m 48s	remaining: 20.7s
84:	learn: 0.8781932	total: 1m 49s	remaining: 19.4s
85:	learn: 0.8777168	total: 1m 51s	remaining: 18.1s
86:	learn: 0.8773966	total: 1m 52s	remaining: 16.8s
87:	learn: 0.8768785	total: 1m 53s	remaining: 15.5s
88:	learn: 0.8763983	total: 1m 54s	remaining: 14.2s
89:	learn: 0.8759693	total: 1m 55s	remaining: 12.9s
90:	learn: 0.8754662	total: 1m 57s	remaining: 11.6s
91:	learn: 0.8747458	total: 1m 58s	remaining: 10.3s
92:	learn: 0.8744557	total: 1m 59s	remaining: 9.02s
93:	learn: 0.8740214	total: 2m 1s	remaining: 7.73s
94:	learn: 0.8737042	total: 2m 2s	remaining: 6.43s
95:	learn: 0.8733902	total: 2m 3s	remaining: 5.14s
96:	learn: 0.8729900	total: 2m 4s	remaining: 3.85s
97:	learn: 0.8727669	total: 2m 5s	remaining: 2.57s
98:	learn: 0.8725891	total: 2m 6s	remaining: 1.28s
99:	learn: 0.8720213	total: 2m 8s	remaining: 0us

# Predict

In [64]:
test['cleaned_text'] = test['text'].apply(
    lambda x: ' '.join(
        token.lemma_.lower() for token in nlp(x) if
        not token.is_stop
        and not token.is_punct
        and not token.is_digit
        and not token.like_email
        and not token.like_num
        and not token.is_space
    )
)

In [66]:
test_vec = TfidfVectorizer(ngram_range = (1,1), max_features = 500)
test_bow = vec.fit_transform(test['cleaned_text'])
predictions = model.predict(test_bow)

In [ ]:
# Preparing data in Pool format
dataset_test = Pool(
    data=X_test,
    text_features=[0]
)
predict_classes = model.predict(dataset_test)
predictions = predict_classes

# Create submission

In [67]:
sample_submission_path = '/content/drive/My Drive/sample_submission.csv'
submission = pd.read_csv(sample_submission_path)
submission["rate"] = predictions
submission.head()

   index  rate
0      0     1
1      1     1
2      2     3
3      3     5
4      4     3

In [70]:
submission_path = '/content/drive/My Drive/submission.csv'
submission.to_csv(submission_path, index=False)