In [23]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Import Libraries

In [46]:
import os
from pathlib import Path

import torch
import pandas as pd
import gensim.downloader as api
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pack_sequence
from numpy import asarray
from torch.nn import CrossEntropyLoss
from sklearn.metrics import classification_report
from torch.optim import Adam
from tqdm.notebook import tqdm


from dataset import *
from model import *
#from trainer import Trainer

import spacy
import nltk


torch.manual_seed(42)

# Read Data

In [25]:
class Trainer:
    def __init__(self, config: Dict):
        """
        Fits end evaluates given model with Adam optimizer.
         Hyperparameters are specified in `config`
        Possible keys are:
            - n_epochs: number of epochs to train
            - lr: optimizer learning rate
            - weight_decay: l2 regularization weight
            - device: on which device to perform training ("cpu" or "cuda")
            - verbose: whether to print anything during training
        :param config: configuration for `Trainer`
        """
        self.config = config
        self.n_epochs = config["n_epochs"]
        self.setup_opt_fn = lambda model: Adam(
            model.parameters(), config["lr"], weight_decay=config["weight_decay"]
        )
        self.model = None
        self.opt = None
        self.history = None
        self.loss_fn = CrossEntropyLoss()
        self.device = config["device"]
        self.verbose = config.get("verbose", True)

    def fit(self, model, train_loader, val_loader):
        """
        Fits model on training data, each epoch evaluates on validation data
        :param model: PyTorch model for toxic comments classification (for example, `RecurrentClassifier`)
        :param train_loader: DataLoader for training data
        :param val_loader: DataLoader for validation data
        :return:
        """
        self.model = model.to(self.device)
        self.opt = self.setup_opt_fn(self.model)
        self.history = {"train_loss": [], "val_loss": [], "val_acc": []}
        for epoch in range(self.n_epochs):
            print(f"Epoch {epoch + 1}/{self.n_epochs}")
            train_info = self._train_epoch(train_loader)
            val_info = self._val_epoch(val_loader)
            self.history["train_loss"].extend(train_info["train_loss"])
            self.history["val_loss"].append(val_info["loss"])
            self.history["val_acc"].append(val_info["acc"])
            print("Val loss ",val_info["loss"])
        return self.model.eval()

    def _train_epoch(self, train_loader):
        self.model.train()
        losses = []
        if self.verbose:
            train_loader = tqdm(train_loader)
        for batch in train_loader:
            self.model.zero_grad()
            texts, labels = batch
            logits = self.model.forward(texts.to(self.device))
            loss = self.loss_fn(logits, labels.to(self.device))
            loss.backward()
            self.opt.step()
            loss_val = loss.item()
            if self.verbose:
                train_loader.set_description(f"Loss={loss_val:.3}")
            losses.append(loss_val)
        return {"train_loss": losses}

    def _val_epoch(self, val_loader):
        self.model.eval()
        all_logits = []
        all_labels = []
        if self.verbose:
            val_loader = tqdm(val_loader)
        with torch.no_grad():
            for batch in val_loader:
                texts, labels = batch
                logits = self.model.forward(texts.to(self.device))
                all_logits.append(logits)
                all_labels.append(labels)
        all_labels = torch.cat(all_labels).to(self.device)
        all_logits = torch.cat(all_logits)
        loss = CrossEntropyLoss()(all_logits, all_labels).item()
        acc = (all_logits.argmax(1) == all_labels).float().mean().item()
        if self.verbose:
            val_loader.set_description(f"Loss={loss:.3}; Acc:{acc:.3}")
        return {"acc": acc, "loss": loss}

    def predict(self, test_loader):
        if self.model is None:
            raise RuntimeError("You should train the model first")
        self.model.eval()
        predictions = []
        with torch.no_grad():
            for batch in test_loader:
                texts, labels = batch
                logits = self.model.forward(texts.to(self.device))
                predictions.extend(logits.argmax(1).tolist())
        return asarray(predictions)

    def save(self, path: str):
        if self.model is None:
            raise RuntimeError("You should train the model first")
        checkpoint = {
            "config": self.model.config,
            "trainer_config": self.config,
            "vocab": self.model.vocab,
            "emb_matrix": self.model.emb_matrix,
            "state_dict": self.model.state_dict(),
        }
        torch.save(checkpoint, path)

    @classmethod
    def load(cls, path: str):
        ckpt = torch.load(path)
        keys = ["config", "trainer_config",
                "vocab", "emb_matrix", "state_dict"]
        for key in keys:
            if key not in ckpt:
                raise RuntimeError(f"Missing key {key} in checkpoint")
        new_model = RecurrentClassifier(
            ckpt["config"], ckpt["vocab"], ckpt["emb_matrix"]
        )
        new_model.load_state_dict(ckpt["state_dict"])
        new_trainer = cls(ckpt["trainer_config"])
        new_trainer.model = new_model
        new_trainer.model.to(new_trainer.device)
        return new_trainer

In [26]:
path = "../../"
train = pd.read_csv(os.path.join(path, "train.csv"))
test = pd.read_csv(os.path.join(path, "test.csv"))

train.head()

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

In [27]:
nlp = spacy.load("ru_core_news_sm")
stopwords = nlp.Defaults.stop_words
print(f'Spacy ru stopwords size: {len(stopwords)}', end='\n\n')
' '.join(stopwords)

Spacy ru stopwords size: 768

'наса немного рано такова щ одной иногда каждые нужный х свой чём мною такою иным притом разве таков кстати бишь л там оно покамест казались эй об этот моей й поприще немногим подобного кой мало подобная едва всеми имело скорее едят наши некуда данному поистине вишь чего уже ей явных нынешнее моим моих сперва похожем поэтому самому моему одни подобных нипочем про чему хе другими той довольно отнелижа этой очевидно кем вот потому после ничему мочь самый особые бывала данного через его давно могу дану ешь наверняка ним стать этим такой некому многому только дальше вами ниоткуда чхать сама бац иначе этакий саму впрямь из никогда комья твой что ую п буду того было многое явно ее оне никому сквозь совсем таки эка смогут еще или чей особенно эх само одними данное котором им тех данном которого вдруг каждый ничто которому нем проще тотчас туда можешь нашему ура слишком моего внакладе ибо коль хотела которые просто моги нигде оный этак ж есть дополнительно отсюда ш на чтоб начале недавно некоторых неё стали такому особо нет оттого далее какого сей казаться воистину самое очень оба тут некто какие всегда казалась снова фу любыми некоторая еле всем подобно сколько своим нашей лишь ай будь иметь другая де якобы ая больше это рядом тьфу али нередко между нечего над ближайшие любая настоящие нынче сего нибудь ту некоторые этих которую каждое данная сродни в могло всего насчет либо близко теми этого самых ю вначале каков под моими них доколь будет каким никак пожалуй б всей ч имъ тобою твои будешь чтобы ый вернее какой многом поскольку сейчас тоже нашем недалеко суть одною вправду которая один а та другие самая каждая сначала ох напрямую находиться мне одну во вон необходимости подобные всякого со ые ежели себе кабы напротив него некоторый эту нужного моя наипаче часто отовсюду должный благодаря му о настоящий свыше сызнова особую ваше ку могли неоткуда нечему всю могут хорошо внизу моем р зачем многие казалось се ых мою которое ах ишь кто те этою потом немногие ау эти вдобавок эдакий авось почти можете именно алло как пор какая тебя вправе нас скоро нашего такие они назад меня этом поелику да которых могите вдали причем самом данунах одного неважно негде хотеть ка ы имеет яко своей нельзя ранее необходимые тобой наоборот вовсе наших самого наизворот моём поколе менее нашею ничем покудова за общую агу почему тем бывают всякой её тогда одному если своя ух чуть у своё короче более собою наша тот нею собственно одних навыворот стал наше опять далеко такое меньше наперекор он к ком таком зато самим я наш ел якоже неужели нужные посреди кого экий вокруг низко ему же должны любое пусть любом ваш такими нынешней около ради так любой поди любого вряд ведь мои вне ты несколько нужных ими спокону будут ней своею ныне весь давным д ага спустя всему вообще ко какими помимо посредством ти бывали вопреки касательно одном самими впрочем вполне стало понеже своему которыми своём з наперед уж одна даже нашим куда всячески мой н от коли меж потомушта своего нём такую необходимым посему среди оттуда ем должна позже вплоть нужная гораздо покуда будем прочего нашими ха будто необходимо твоё ща все однажды е насилу ела нечто нате хотел был но прежде одним мимо моё имел однако томах нешто другое мы накануне нечем включая прям одно нее г была может всё вчеред чьих кроме дабы давайте вниз нами ничего вместо до с чьё сих наконец твоим кому откуда имела всею всея всём зря ну такого много нету иными всякий которой подобный благо доколе будьте том тебе ними ом можно точно должен отнелиже данной го другим ой например нашу хочешь и вперекор вы который вроде то незачем чьим без бываю пока наверху отчему бы начала оп можем щас бывает всех будучи собой твоя хочу она сверх любую подавно безусловно не казался этому должно подобным вся хуже сам какому прочими тою везде данных никакой прочее ваши затем наизнанку э такая данный здесь самих пожалуйста некогда свою отчего где раньше будете нему хоть стала сможет которою мной этими себя ваша оттот своем гав мое эта нам своих также были настоящее другой вам едим нужно хотя бытует м данные всюду ею долго никого ещё мог вас аж обычно чем самой таких ест других эдак любых могла которым при сами никуда какою моею ша ого взаимно нынешних поколь тому быть чё тая возможно вновь ф пора многого следует вресноту сразу теперь действительно наподобие настоящая таким надо прочему видно увы перед наиболее ниже некем взаправду непрерывно их итак свое ли даром навряд чаще мол своими по никем конечно твоих значит паче для кажется свои иль хотелось сие емъ когда никто'

In [28]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/vaa2804/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
nltk_stopwords = nltk.corpus.stopwords.words("russian")
print(f'NLTK ru stopwords size: {len(nltk_stopwords)}', end='\n\n')
' '.join(nltk_stopwords)

NLTK ru stopwords size: 151

'и в во не что он на я с со как а то все она так его но да ты к у же вы за бы по только ее мне было вот от меня еще нет о из ему теперь когда даже ну вдруг ли если уже или ни быть был него до вас нибудь опять уж вам ведь там потом себя ничего ей может они тут где есть надо ней для мы тебя их чем была сам чтоб без будто чего раз тоже себе под будет ж тогда кто этот того потому этого какой совсем ним здесь этом один почти мой тем чтобы нее сейчас были куда зачем всех никогда можно при наконец два об другой хоть после над больше тот через эти нас про всего них какая много разве три эту моя впрочем хорошо свою этой перед иногда лучше чуть том нельзя такой им более всегда конечно всю между'

In [30]:
nltk_stopwords[:10]

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со']

In [31]:
nlp.stopwords = nltk_stopwords[:100]

In [32]:
train['text'] = train['text'].apply(
    lambda x: ' '.join(
        token.lemma_.lower() for token in nlp(x) if
        not token.is_stop
        and not token.is_punct
        and not token.is_digit
        and not token.like_email
        and not token.like_num
        and not token.is_space
    )
)

# Label encoding

In [33]:
le = LabelEncoder()

train.rate = le.fit_transform(train.rate)
train.head()

   rate                                               text
0     3  понравиться март собака дойти лесной озеро зко...
1     4  целое магазин устраивать ассортимент позволять...
2     4                                    открыться ехать
3     2  громко объявить заботиться пенсионер установит...
4     2  тесно вечный сутолока ряд трудный разойтись гр...

In [34]:
train.describe()

               rate
count  48665.000000
mean       3.055666
std        1.273523
min        0.000000
25%        2.000000
50%        4.000000
75%        4.000000
max        4.000000

# Create pretrained tokenizers

In [35]:
tok = Tokenizer()
tok_texts = [tok.tokenize(t) for t in train.text.values]
vocab = Vocab(tok_texts, max_vocab_size=30000)

In [36]:
tok_texts[:5]

[['понравиться',
  'март',
  'собака',
  'дойти',
  'лесной',
  'озеро',
  'зкотропе',
  'собака',
  'набегаться',
  'нагулялись',
  'домик',
  'чистый',
  'цена',
  'соответствовать',
  'рекомендовать',
  'взять',
  'посуда'],
 ['целое',
  'магазин',
  'устраивать',
  'ассортимент',
  'позволять',
  'ходить',
  'магазин',
  'покупать',
  'дом',
  'акция',
  'сроки',
  'годность',
  'соответствовать',
  'кассир',
  'доброжелательный',
  'правда',
  'последний',
  'год',
  'количество',
  'уменьшиться',
  'раз',
  'работать',
  'касса',
  'очередь',
  'магазин',
  'чисто',
  'размораживать',
  'мыть',
  'холодильник',
  'заходить',
  'неделя',
  'какой',
  'ходовой',
  'товаров',
  'курица',
  'творог',
  'т',
  'д'],
 ['открыться', 'ехать'],
 ['громко',
  'объявить',
  'заботиться',
  'пенсионер',
  'установить',
  'час',
  'посещение',
  'магазин',
  'сеть',
  'заразиться',
  'короновирусом',
  'иметь',
  'время',
  'хлеба',
  'морковь',
  'лимон',
  'т',
  'д',
  'объяснять',
  'завоза',
  'приглашать'],
 ['тесно',
  'вечный',
  'сутолока',
  'ряд',
  'трудный',
  'разойтись',
  'грязный',
  'пара',
  'раз',
  'пойти']]

In [37]:
vocab.__len__()

29023

In [38]:
vocab.itos[:10]

['<PAD>',
 '<UNK>',
 '<EOS>',
 'магазин',
 'хороший',
 'товар',
 'касса',
 'персонал',
 'ассортимент',
 'удобный']

# Splitting Data

In [39]:
train_texts, train_labels, val_texts, val_labels = train_test_split(train)
train_dataset = TextDataset([tok.tokenize(t)
                            for t in train_texts], train_labels, vocab)
val_dataset = TextDataset([tok.tokenize(t)
                          for t in val_texts], val_labels, vocab)

In [40]:
train_texts[:5]

['цена касса вечно соответствовать цена зал внимательный обходить сторона',
 'отвратительный товар полка ассортимент',
 'постоянный мухлеж ценник остальном хороший магнит дикси',
 'маленький тесный магазин полка лежать просрочка касаться мясной продукция',
 'разочарование магазин овощ никакой вялый картофель свежий единственный плюс свежий выпечка свежий']

In [41]:
train_dataset.texts[:2]

[['цена',
  'касса',
  'вечно',
  'соответствовать',
  'цена',
  'зал',
  'внимательный',
  'обходить',
  'сторона'],
 ['отвратительный', 'товар', 'полка', 'ассортимент']]

In [42]:
train_dataset.__getitem__(0)

([10, 6, 159, 69, 10, 44, 136, 784, 168, 2], 0)

# Create embeddings from tokens

In [43]:
os.environ["GENSIM_DATA_DIR"] = str(Path.cwd())
gensim_model = api.load("word2vec-ruscorpora-300")
emb_matrix = prepare_emb_matrix(gensim_model, vocab)

# Init Model and Config

In [48]:
config = {
    "freeze": False,
    "cell_type": "LSTM",
    "cell_dropout": 0.2,
    "num_layers": 2,
    "hidden_size": 128,
    "out_activation": "relu",
    "bidirectional": True,
    "out_dropout": 0.2,
    "out_sizes": [200],
}

trainer_config = {
    "lr": 3e-3,
    "n_epochs": 5,
    "weight_decay": 1e-5,
    "batch_size": 128,
    "device": "cuda" if torch.cuda.is_available() else "cpu"
}
clf_model = RecurrentClassifier(config, vocab, emb_matrix)

# Create Dataloaders and Train

In [49]:
train_dataloader = DataLoader(train_dataset,
                              batch_size=trainer_config["batch_size"],
                              shuffle=True,
                              num_workers=0,
                              collate_fn=train_dataset.collate_fn)
val_dataloader = DataLoader(val_dataset,
                            batch_size=trainer_config["batch_size"],
                            shuffle=False,
                            num_workers=0,
                            collate_fn=val_dataset.collate_fn)
t = Trainer(trainer_config)
t.fit(clf_model, train_dataloader, val_dataloader)

Epoch 1/5

  0%|          | 0/324 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

Train loss  [1.8064523935317993, 1.5921828746795654, 1.2226734161376953, 1.4356168508529663, 1.5454312562942505, 1.1617356538772583, 1.2345975637435913, 1.2621084451675415, 1.1606181859970093, 1.0408101081848145, 0.9769644737243652, 0.9937536120414734, 1.0956122875213623, 1.0303277969360352, 0.8861694931983948, 0.9230989813804626, 0.9272538423538208, 0.9017505049705505, 0.9094640612602234, 0.9631466865539551, 0.9183959364891052, 1.116673469543457, 0.9633764028549194, 0.8728729486465454, 0.9447911381721497, 0.8054189085960388, 0.8240413665771484, 0.9646854996681213, 0.9433165192604065, 0.9562667608261108, 0.8600761294364929, 0.8183967471122742, 0.8175795078277588, 0.8398489952087402, 0.8507928848266602, 0.8129183650016785, 0.8836572170257568, 0.8828200101852417, 0.8810104727745056, 0.7335713505744934, 0.81934654712677, 0.835889995098114, 0.9033359885215759, 0.934067964553833, 0.9306219220161438, 0.8887559771537781, 0.9998186826705933, 0.8010432124137878, 0.8229913115501404, 0.7908316254615784, 0.929498016834259, 0.7723444104194641, 0.919108510017395, 0.7712910175323486, 0.9326856136322021, 0.8246647119522095, 0.8219727873802185, 0.8642393350601196, 0.8081194758415222, 0.8586442470550537, 0.8471707105636597, 0.8212324380874634, 0.8495489954948425, 0.9153943061828613, 0.7702175378799438, 0.7524296045303345, 0.8221060633659363, 0.9871898293495178, 0.9676393270492554, 0.8767852783203125, 0.7740417122840881, 0.7947998642921448, 0.7875881195068359, 0.9273688793182373, 0.8725483417510986, 0.8346657752990723, 0.7760239243507385, 0.6504372358322144, 0.8548572063446045, 0.7902894020080566, 0.8119819164276123, 0.9476107358932495, 0.9290339946746826, 0.820504367351532, 0.861950159072876, 0.7847007513046265, 0.8283715844154358, 0.7945723533630371, 0.8590890169143677, 0.6409111618995667, 0.89048171043396, 0.9933496117591858, 1.11029052734375, 1.0227586030960083, 0.8471645712852478, 0.8137038946151733, 0.7624249458312988, 0.8235794305801392, 0.8230573534965515, 0.7531096935272217, 0.7718467116355896, 0.7013775706291199, 0.7662177085876465, 0.9586306810379028, 0.8659815788269043, 0.8585453033447266, 0.6849669218063354, 0.8831422924995422, 0.8440598249435425, 0.7527563571929932, 0.8093768954277039, 0.6903463006019592, 0.7742316722869873, 0.9113419055938721, 0.795569896697998, 0.7838470339775085, 0.8631012439727783, 0.9464132189750671, 0.8027780055999756, 0.7138087153434753, 0.7860071659088135, 0.8370945453643799, 0.6936183571815491, 0.7564687728881836, 0.8244857788085938, 0.7759969234466553, 0.698021411895752, 0.7882197499275208, 0.6736137866973877, 0.7212004065513611, 0.8147900104522705, 0.7097407579421997, 0.7501217722892761, 0.8017681837081909, 0.8694425821304321, 0.8761212825775146, 0.9396188855171204, 0.7239102125167847, 0.7668159604072571, 0.8058820962905884, 0.7713754177093506, 0.881363034248352, 0.8645803928375244, 0.8224565386772156, 0.8625929355621338, 0.7972431182861328, 0.7871755361557007, 0.8419541120529175, 0.9259073138237, 0.9059067368507385, 0.8057860136032104, 0.9170992374420166, 0.7943874001502991, 0.9056485891342163, 0.9792107939720154, 0.8776097297668457, 0.6752192974090576, 0.8769353032112122, 0.8290451169013977, 0.9015266299247742, 0.8684800267219543, 0.7708057761192322, 0.9027562737464905, 0.8747373819351196, 0.8443319201469421, 0.6064662337303162, 0.7647163271903992, 0.8882336616516113, 0.8921574950218201, 0.7949114441871643, 0.7629898190498352, 0.8520179986953735, 0.9033874869346619, 0.9540954232215881, 0.7211630940437317, 0.7518770098686218, 1.0560290813446045, 0.7741628289222717, 0.7291309833526611, 0.8401986360549927, 0.7910617589950562, 0.5997996926307678, 0.8130578398704529, 0.8134139180183411, 0.720348060131073, 0.8826174736022949, 0.7424300909042358, 0.9759895205497742, 0.8343722820281982, 0.824531614780426, 0.8867962956428528, 0.9167123436927795, 0.7096259593963623, 0.8778479099273682, 0.7390069365501404, 0.8631232976913452, 0.8130325078964233, 0.6572575569152832, 0.8975154757499695, 0.9460649490356445, 0.8261759281158447, 0.7905833721160889, 0.8534798622131348, 0.8159846067428589, 0.8561144471168518, 0.8342953324317932, 0.8349683284759521, 0.7872352600097656, 0.748470664024353, 0.9001393914222717, 0.9652529358863831, 0.7559412717819214, 0.9216387271881104, 0.7556396126747131, 0.805753231048584, 0.7723027467727661, 0.9018513560295105, 0.7085151076316833, 0.7843836545944214, 0.8650661706924438, 0.8290765285491943, 0.8603493571281433, 0.8503302931785583, 0.8778173327445984, 0.7048938870429993, 0.6807643175125122, 0.7895132303237915, 0.8271873593330383, 0.916591465473175, 0.8815687298774719, 0.7597204446792603, 0.7176158428192139, 0.7825244069099426, 0.7583927512168884, 0.6852136254310608, 0.6745844483375549, 0.8832142949104309, 0.7836855053901672, 0.7894298434257507, 0.8577774167060852, 0.7482274770736694, 0.8977009654045105, 0.7932068705558777, 0.7580836415290833, 0.9025755524635315, 0.7173144221305847, 0.6800961494445801, 0.8911134600639343, 0.6941982507705688, 0.7538858652114868, 0.9189404845237732, 0.8853591084480286, 0.6856686472892761, 0.7031311392784119, 0.8254380226135254, 0.8744627237319946, 0.8598836660385132, 0.7719000577926636, 0.7624149322509766, 0.9243178367614746, 0.73873370885849, 1.0077813863754272, 0.801084578037262, 0.796931266784668, 0.7904320359230042, 0.7542594075202942, 0.8733418583869934, 0.6984858512878418, 0.881919801235199, 0.8161426782608032, 0.7463828325271606, 0.7750749588012695, 0.7502744793891907, 1.0302505493164062, 0.7518600821495056, 0.8201932311058044, 0.8166832327842712, 0.9526374936103821, 0.722991943359375, 0.8457752466201782, 0.894370436668396, 0.8902650475502014, 0.7482020258903503, 0.8799722790718079, 0.8139787316322327, 0.8175763487815857, 0.8537521362304688, 0.7802149057388306, 0.8424250483512878, 0.7912319302558899, 0.7704534530639648, 0.7214897274971008, 0.8414462208747864, 0.8761662840843201, 0.8004681468009949, 0.7929960489273071, 0.8675352334976196, 0.8256945013999939, 0.7789669036865234, 0.7495377063751221, 0.748742401599884, 0.7083988189697266, 0.8034006953239441, 0.783409595489502, 0.8078262805938721, 0.7730517387390137, 0.765592098236084, 0.8108929395675659, 0.7019633054733276, 0.8406947255134583, 0.9095137119293213, 0.733568549156189, 0.6897912621498108, 0.8036222457885742, 0.779606282711029, 0.7943000197410583, 0.843930184841156, 0.8168329000473022, 0.8276907801628113, 0.8145821690559387, 0.753057599067688, 0.9018508791923523, 0.8129553198814392, 1.1304453611373901]
Val loss  0.9369635581970215
Epoch 2/5

  0%|          | 0/324 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

Train loss  [0.6213668584823608, 0.6022708415985107, 0.6046729683876038, 0.8044347763061523, 0.6809426546096802, 0.597564697265625, 0.6218279600143433, 0.6045822501182556, 0.5804550051689148, 0.6411044001579285, 0.6470703482627869, 0.4977177381515503, 0.45396631956100464, 0.6343008875846863, 0.46363145112991333, 0.5693344473838806, 0.6064525842666626, 0.5145303606987, 0.41200923919677734, 0.474025160074234, 0.6364811658859253, 0.6391309499740601, 0.6178921461105347, 0.6208547949790955, 0.5189958810806274, 0.5913437604904175, 0.6725634336471558, 0.5768111944198608, 0.5161792635917664, 0.5497432947158813, 0.6212291121482849, 0.5123370289802551, 0.4620696008205414, 0.5603947043418884, 0.7341353297233582, 0.4445273280143738, 0.6678146719932556, 0.6069945693016052, 0.4766353964805603, 0.5780718922615051, 0.582444965839386, 0.5273430943489075, 0.4523967504501343, 0.4666009247303009, 0.5832430720329285, 0.4941226840019226, 0.5278899669647217, 0.5414745807647705, 0.6511722803115845, 0.5121996998786926, 0.6814513206481934, 0.6730347871780396, 0.566949188709259, 0.527284562587738, 0.5791048407554626, 0.6165255904197693, 0.6456418633460999, 0.5334706902503967, 0.608897864818573, 0.4304613769054413, 0.4910465478897095, 0.5406594276428223, 0.5475841164588928, 0.6123129725456238, 0.6304898858070374, 0.6512188911437988, 0.6683422923088074, 0.3850201368331909, 0.5662437081336975, 0.5243837237358093, 0.4258229732513428, 0.5727686882019043, 0.7245051860809326, 0.5059753060340881, 0.5382602214813232, 0.49521467089653015, 0.599599301815033, 0.6981565952301025, 0.5157449841499329, 0.5755633115768433, 0.6350827217102051, 0.7170510292053223, 0.7192115783691406, 0.6102938055992126, 0.5933945775032043, 0.6662629842758179, 0.46441441774368286, 0.6920745372772217, 0.79899662733078, 0.5690532326698303, 0.5253121256828308, 0.5673148036003113, 0.5252817869186401, 0.6103036999702454, 0.7340982556343079, 0.5379869341850281, 0.6170599460601807, 0.5686704516410828, 0.5299800634384155, 0.4496169090270996, 0.8553350567817688, 0.4962579607963562, 0.7303786277770996, 0.6364680528640747, 0.522864580154419, 0.5263769626617432, 0.58079594373703, 0.7007767558097839, 0.6256922483444214, 0.5896452069282532, 0.59775710105896, 0.5624963045120239, 0.6391761898994446, 0.5901995301246643, 0.6421209573745728, 0.6180854439735413, 0.6375699043273926, 0.624413788318634, 0.5671883821487427, 0.579704761505127, 0.5234670042991638, 0.5963464975357056, 0.7166200876235962, 0.5720476508140564, 0.6256265044212341, 0.5260739922523499, 0.49531522393226624, 0.5848307609558105, 0.5509863495826721, 0.7206010222434998, 0.6089357733726501, 0.7216176986694336, 0.6899839043617249, 0.6358528137207031, 0.545282781124115, 0.5203964114189148, 0.6445284485816956, 0.5231462121009827, 0.608146071434021, 0.5432926416397095, 0.5790846943855286, 0.6261224746704102, 0.5990519523620605, 0.5631157159805298, 0.6796913146972656, 0.6182888150215149, 0.5992522239685059, 0.5571503043174744, 0.5823819637298584, 0.6480439305305481, 0.5819557309150696, 0.6212343573570251, 0.5492446422576904, 0.500171422958374, 0.6224302649497986, 0.5507115721702576, 0.567959725856781, 0.6243538856506348, 0.6577049493789673, 0.5587864518165588, 0.6293420195579529, 0.5874519944190979, 0.470735639333725, 0.5698173642158508, 0.6469322443008423, 0.525032103061676, 0.5904761552810669, 0.622033417224884, 0.6330554485321045, 0.5693714618682861, 0.7918200492858887, 0.6813477277755737, 0.595678448677063, 0.6996049284934998, 0.6692342758178711, 0.7339334487915039, 0.6262814402580261, 0.5704437494277954, 0.7271423935890198, 0.5613564848899841, 0.7018503546714783, 0.6371086239814758, 0.5898762941360474, 0.7249086499214172, 0.612978994846344, 0.5909340977668762, 0.5333302021026611, 0.7241623997688293, 0.5754873752593994, 0.6232994794845581, 0.8231489062309265, 0.7341157793998718, 0.5711926817893982, 0.5426146984100342, 0.6847524046897888, 0.5622951984405518, 0.6746159195899963, 0.7449882626533508, 0.6383698582649231, 0.6491358280181885, 0.7912436127662659, 0.6016172766685486, 0.6468727588653564, 0.6373583674430847, 0.563454806804657, 0.6632665991783142, 0.6626216769218445, 0.6289240717887878, 0.6255768537521362, 0.5282441973686218, 0.6227951049804688, 0.6442314386367798, 0.7323034405708313, 0.7406589984893799, 0.6299638748168945, 0.695946991443634, 0.5962673425674438, 0.6596865057945251, 0.49044764041900635, 0.6634541749954224, 0.4814535677433014, 0.670825719833374, 0.7226611375808716, 0.6257539987564087, 0.6402194499969482, 0.598029375076294, 0.7042688727378845, 0.5927343368530273, 0.6534070372581482, 0.7730581164360046, 0.6111372113227844, 0.7353113889694214, 0.6563155651092529, 0.6414751410484314, 0.5818233489990234, 0.568328320980072, 0.6839584708213806, 0.74628084897995, 0.6678312420845032, 0.5802473425865173, 0.6320568323135376, 0.6472482085227966, 0.6707186102867126, 0.6428742408752441, 0.5337709188461304, 0.7956908345222473, 0.7391594648361206, 0.8072883486747742, 0.6457870006561279, 0.5020322799682617, 0.5910021066665649, 0.5220938324928284, 0.7522940635681152, 0.4998369812965393, 0.6173098087310791, 0.6856322288513184, 0.7172293066978455, 0.6166195273399353, 0.5326851606369019, 0.5697930455207825, 0.6060883402824402, 0.6095950603485107, 0.556620717048645, 0.6064327359199524, 0.7782063484191895, 0.7044824361801147, 0.6292278170585632, 0.7231771349906921, 0.5820214152336121, 0.6701505184173584, 0.6930089592933655, 0.7500467896461487, 0.505956768989563, 0.7122635841369629, 0.6409645080566406, 0.8117573261260986, 0.6633837819099426, 0.7467833161354065, 0.6483546495437622, 0.6641080379486084, 0.6592943072319031, 0.7912642955780029, 0.732309877872467, 0.5888417363166809, 0.7090924382209778, 0.6487405300140381, 0.6599697470664978, 0.5932556986808777, 0.7535539269447327, 0.5464549660682678, 0.6753878593444824, 0.6496589779853821, 0.7524122595787048, 0.625845193862915, 0.8075209259986877, 0.7056641578674316, 0.5560732483863831, 0.5513319373130798, 0.7956550717353821, 0.5057411789894104, 0.530160129070282, 0.6755285263061523, 0.7500461935997009, 0.7273625135421753, 0.6621775031089783, 0.7256342768669128, 0.7976875901222229, 0.6848050355911255, 0.6119170188903809, 0.6469183564186096, 0.5931065082550049, 0.6625251770019531, 0.7703964710235596, 0.5331234931945801, 0.7160988450050354, 0.632231593132019, 0.6184357404708862, 0.6592137217521667, 0.6721591353416443, 0.8295719623565674, 0.7942360043525696, 0.7576035261154175, 0.6153243184089661, 0.6802383065223694]
Val loss  1.0770115852355957
Epoch 3/5

  0%|          | 0/324 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

Train loss  [0.36608636379241943, 0.37696659564971924, 0.3736882507801056, 0.45579925179481506, 0.29419994354248047, 0.37613072991371155, 0.451397567987442, 0.3555092215538025, 0.34583142399787903, 0.4041336476802826, 0.42819344997406006, 0.343778520822525, 0.4442000389099121, 0.3340330719947815, 0.41404491662979126, 0.36392393708229065, 0.3821633458137512, 0.37162506580352783, 0.40246325731277466, 0.4010411202907562, 0.4104510545730591, 0.32346129417419434, 0.3778494894504547, 0.3363182842731476, 0.3828577399253845, 0.4392627477645874, 0.35281115770339966, 0.3255973160266876, 0.2957589626312256, 0.3476957082748413, 0.3933955729007721, 0.35616397857666016, 0.2556869089603424, 0.48096373677253723, 0.31551653146743774, 0.3107447028160095, 0.2942008376121521, 0.327246755361557, 0.3293645679950714, 0.3263411223888397, 0.2771216928958893, 0.4136389195919037, 0.3045680820941925, 0.3357241451740265, 0.40525442361831665, 0.28460612893104553, 0.3647739291191101, 0.46871283650398254, 0.40231144428253174, 0.42190465331077576, 0.39145079255104065, 0.3780784010887146, 0.32863253355026245, 0.5228450298309326, 0.38477566838264465, 0.40306249260902405, 0.3837811052799225, 0.4011956751346588, 0.361662894487381, 0.20688346028327942, 0.43358784914016724, 0.5095207095146179, 0.4632299244403839, 0.42344778776168823, 0.2641158401966095, 0.4584382176399231, 0.33132603764533997, 0.30780550837516785, 0.3499206304550171, 0.4043976366519928, 0.31480446457862854, 0.3387832045555115, 0.39792996644973755, 0.43307608366012573, 0.4220113456249237, 0.4357174336910248, 0.4308854043483734, 0.3590768575668335, 0.3587805926799774, 0.33692702651023865, 0.3456736207008362, 0.43011194467544556, 0.4467158615589142, 0.3109707236289978, 0.41140589118003845, 0.3663579225540161, 0.46540117263793945, 0.396890789270401, 0.4632571339607239, 0.33503058552742004, 0.34569981694221497, 0.42826515436172485, 0.3453356623649597, 0.5015878677368164, 0.4056873321533203, 0.3447009325027466, 0.3283320665359497, 0.4350845217704773, 0.5520754456520081, 0.4112339913845062, 0.39433738589286804, 0.501253604888916, 0.37479299306869507, 0.31303319334983826, 0.31949469447135925, 0.5336614847183228, 0.3615655303001404, 0.3688535988330841, 0.36764490604400635, 0.3575041890144348, 0.4092855155467987, 0.28838691115379333, 0.48600324988365173, 0.3268575668334961, 0.29686999320983887, 0.37533673644065857, 0.3145458698272705, 0.607614278793335, 0.4006906747817993, 0.31950294971466064, 0.3525192439556122, 0.34045398235321045, 0.35275816917419434, 0.4262771010398865, 0.4584197998046875, 0.500531017780304, 0.4450867474079132, 0.45809507369995117, 0.48939934372901917, 0.4626188278198242, 0.4336240887641907, 0.2585763931274414, 0.3730466067790985, 0.3482189178466797, 0.38910266757011414, 0.3384872376918793, 0.32651567459106445, 0.46731698513031006, 0.3512200117111206, 0.38164642453193665, 0.4157465398311615, 0.40803080797195435, 0.44814977049827576, 0.516775906085968, 0.4314200282096863, 0.378415048122406, 0.48869356513023376, 0.3441650867462158, 0.4950965642929077, 0.31984856724739075, 0.4609256386756897, 0.41801685094833374, 0.4189262390136719, 0.495559960603714, 0.5044229626655579, 0.41081520915031433, 0.5559532046318054, 0.3168584704399109, 0.4467114508152008, 0.4580942988395691, 0.38248634338378906, 0.32806089520454407, 0.2991935908794403, 0.4236304461956024, 0.41363391280174255, 0.4426308870315552, 0.540786862373352, 0.4389815628528595, 0.3511447310447693, 0.36887508630752563, 0.38882744312286377, 0.33580777049064636, 0.3615151047706604, 0.33935198187828064, 0.4642927944660187, 0.4656226933002472, 0.28716403245925903, 0.5065791010856628, 0.5815348625183105, 0.3548316955566406, 0.4594358503818512, 0.3987632393836975, 0.4527236819267273, 0.41580885648727417, 0.4601720869541168, 0.5659162998199463, 0.4603005349636078, 0.4826434850692749, 0.5446577072143555, 0.46913596987724304, 0.4820628762245178, 0.4362069368362427, 0.39668509364128113, 0.4247714877128601, 0.4014997184276581, 0.5067071914672852, 0.3615666925907135, 0.4752868115901947, 0.40368425846099854, 0.42722758650779724, 0.47357383370399475, 0.45077261328697205, 0.4034670889377594, 0.4819625914096832, 0.3384075164794922, 0.396291583776474, 0.39194098114967346, 0.40286827087402344, 0.45299232006073, 0.4207247197628021, 0.4777766764163971, 0.45963114500045776, 0.42028579115867615, 0.5247692465782166, 0.4660146236419678, 0.43371260166168213, 0.5551778078079224, 0.3579978048801422, 0.45472925901412964, 0.42389801144599915, 0.41776180267333984, 0.35416746139526367, 0.5129591226577759, 0.33797910809516907, 0.5030199885368347, 0.38063299655914307, 0.379305899143219, 0.4282885193824768, 0.44784095883369446, 0.30646318197250366, 0.312404990196228, 0.4216846823692322, 0.5263679027557373, 0.3019217550754547, 0.41050031781196594, 0.38676974177360535, 0.5083427429199219, 0.35504257678985596, 0.4575645625591278, 0.28200000524520874, 0.5577645301818848, 0.6273047924041748, 0.41806668043136597, 0.4458383023738861, 0.4325218200683594, 0.5238834619522095, 0.3697228729724884, 0.34853020310401917, 0.5063512325286865, 0.5923348665237427, 0.468742698431015, 0.5048060417175293, 0.5146983861923218, 0.5037252306938171, 0.42414143681526184, 0.4432540237903595, 0.4831433892250061, 0.4752075970172882, 0.4606020450592041, 0.5968175530433655, 0.6015880703926086, 0.46248096227645874, 0.4209853708744049, 0.38020721077919006, 0.4438773989677429, 0.5136604309082031, 0.43363067507743835, 0.4743441045284271, 0.36445119976997375, 0.4411461651325226, 0.4481639564037323, 0.43433085083961487, 0.4048537313938141, 0.38690492510795593, 0.4490066468715668, 0.43110907077789307, 0.46181192994117737, 0.4305773377418518, 0.33901146054267883, 0.44066131114959717, 0.23538081347942352, 0.5534735918045044, 0.4121639132499695, 0.4170595705509186, 0.35911840200424194, 0.4328286647796631, 0.506719708442688, 0.39047738909721375, 0.4807787537574768, 0.5888841152191162, 0.4762120246887207, 0.47653868794441223, 0.37536874413490295, 0.4237841069698334, 0.5330033302307129, 0.4991235136985779, 0.5423704385757446, 0.5879206657409668, 0.40916845202445984, 0.4694729149341583, 0.45507195591926575, 0.44681987166404724, 0.584119439125061, 0.48925748467445374, 0.48360592126846313, 0.4861021339893341, 0.4414817988872528, 0.44830626249313354, 0.49305635690689087, 0.4193020164966583, 0.6816849112510681, 0.5282418727874756, 0.48833605647087097, 0.4467658996582031, 0.545341968536377, 0.5584681034088135, 0.4966084659099579, 0.40014249086380005, 0.6235859394073486, 0.4356330335140228, 0.4423111081123352, 0.47157829999923706, 0.5484703779220581, 0.7315149307250977]
Val loss  1.3302034139633179
Epoch 4/5

  0%|          | 0/324 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

Train loss  [0.22725339233875275, 0.2518540620803833, 0.3961808681488037, 0.36150094866752625, 0.26526251435279846, 0.4515077769756317, 0.30476894974708557, 0.24636772274971008, 0.32903629541397095, 0.3738667070865631, 0.22628438472747803, 0.2669571042060852, 0.3312516212463379, 0.3120933771133423, 0.34154772758483887, 0.28672119975090027, 0.2731322646141052, 0.44326287508010864, 0.40787988901138306, 0.3117011785507202, 0.40674668550491333, 0.2642173171043396, 0.2920769155025482, 0.19018736481666565, 0.46355175971984863, 0.3411451280117035, 0.4030241072177887, 0.2525096833705902, 0.292729914188385, 0.3874954283237457, 0.2677655816078186, 0.3935098946094513, 0.32567304372787476, 0.33857661485671997, 0.4175581932067871, 0.3313344419002533, 0.36520981788635254, 0.3179677426815033, 0.2705135643482208, 0.31935811042785645, 0.27606305480003357, 0.3480052947998047, 0.30434346199035645, 0.3093259334564209, 0.20529420673847198, 0.24002942442893982, 0.22724592685699463, 0.2261514663696289, 0.20953664183616638, 0.24699324369430542, 0.19916193187236786, 0.32572346925735474, 0.3046616315841675, 0.3515951335430145, 0.29309016466140747, 0.2880052626132965, 0.24085736274719238, 0.27793046832084656, 0.3334132730960846, 0.3976941704750061, 0.252726674079895, 0.3677525222301483, 0.2789051830768585, 0.2543460726737976, 0.3180881440639496, 0.2889690697193146, 0.3905085325241089, 0.3469253182411194, 0.3406897485256195, 0.25692325830459595, 0.3379649221897125, 0.33730682730674744, 0.2941177189350128, 0.19383423030376434, 0.18282416462898254, 0.3630503714084625, 0.455907940864563, 0.41718196868896484, 0.3454405963420868, 0.33970391750335693, 0.2141885757446289, 0.23861485719680786, 0.44877317547798157, 0.3045360743999481, 0.2785528898239136, 0.2840253710746765, 0.25284990668296814, 0.2503075897693634, 0.44776320457458496, 0.28863632678985596, 0.27907511591911316, 0.2797389328479767, 0.2916661500930786, 0.37093275785446167, 0.3265050947666168, 0.2978264093399048, 0.40097567439079285, 0.38138505816459656, 0.2982112467288971, 0.2976571321487427, 0.1938733458518982, 0.4030561149120331, 0.297964870929718, 0.35260990262031555, 0.3739645779132843, 0.35454991459846497, 0.3122554421424866, 0.31999385356903076, 0.2479437291622162, 0.2903795838356018, 0.40240830183029175, 0.4200904071331024, 0.27182409167289734, 0.22962099313735962, 0.24051667749881744, 0.28879788517951965, 0.28925952315330505, 0.24130572378635406, 0.3071625828742981, 0.2211133986711502, 0.2301999032497406, 0.3660150468349457, 0.36785367131233215, 0.27520328760147095, 0.2590658962726593, 0.27469736337661743, 0.31391915678977966, 0.30305808782577515, 0.40609636902809143, 0.3437363803386688, 0.19362717866897583, 0.27570077776908875, 0.4052877426147461, 0.41692429780960083, 0.38542836904525757, 0.26605939865112305, 0.3296879827976227, 0.33945730328559875, 0.2484467774629593, 0.31972792744636536, 0.2612931728363037, 0.35443294048309326, 0.19729460775852203, 0.3402175009250641, 0.31809747219085693, 0.4017024040222168, 0.36421847343444824, 0.2551730275154114, 0.36573895812034607, 0.2582792639732361, 0.37612640857696533, 0.2444549798965454, 0.32585591077804565, 0.3810867369174957, 0.4085918366909027, 0.4354259967803955, 0.31370875239372253, 0.40188834071159363, 0.395031601190567, 0.27319231629371643, 0.49725639820098877, 0.3048620820045471, 0.37280282378196716, 0.2516227066516876, 0.2917427718639374, 0.2726368308067322, 0.35141226649284363, 0.32612112164497375, 0.32068848609924316, 0.4086627960205078, 0.2771227955818176, 0.3740116059780121, 0.27107352018356323, 0.40262821316719055, 0.2515837252140045, 0.2937707006931305, 0.3098010718822479, 0.2690034806728363, 0.2959049344062805, 0.22962349653244019, 0.28195488452911377, 0.31435343623161316, 0.3190940320491791, 0.3543702960014343, 0.37051764130592346, 0.3810368478298187, 0.32630738615989685, 0.2681313753128052, 0.3798747956752777, 0.3551993668079376, 0.42784833908081055, 0.37675365805625916, 0.38692915439605713, 0.3125200867652893, 0.4201558232307434, 0.3491351008415222, 0.31684598326683044, 0.47402721643447876, 0.28769800066947937, 0.3252463936805725, 0.25999221205711365, 0.2813647389411926, 0.3548280894756317, 0.4233148694038391, 0.2572648227214813, 0.38968127965927124, 0.36009681224823, 0.5369040369987488, 0.3265710771083832, 0.3048248887062073, 0.47158199548721313, 0.26333674788475037, 0.3712422549724579, 0.3351001739501953, 0.4239896237850189, 0.3599081039428711, 0.37586188316345215, 0.2805284857749939, 0.5108283758163452, 0.29358452558517456, 0.4973467290401459, 0.30167555809020996, 0.21488410234451294, 0.348886638879776, 0.3775075674057007, 0.33049115538597107, 0.4139115810394287, 0.3445070683956146, 0.39657774567604065, 0.409766286611557, 0.3945187032222748, 0.3071177005767822, 0.4520992338657379, 0.4035077393054962, 0.47638097405433655, 0.4074419438838959, 0.3354162275791168, 0.30617886781692505, 0.39190343022346497, 0.3851310610771179, 0.29316478967666626, 0.38616278767585754, 0.3189324736595154, 0.3775319755077362, 0.4335792064666748, 0.31575071811676025, 0.311284601688385, 0.40265485644340515, 0.2928403913974762, 0.5400736331939697, 0.29502084851264954, 0.49152421951293945, 0.38088417053222656, 0.45378851890563965, 0.32910844683647156, 0.31585991382598877, 0.4507001042366028, 0.286312073469162, 0.6302592158317566, 0.35674259066581726, 0.3388468325138092, 0.5234091877937317, 0.4243163764476776, 0.3307158052921295, 0.3489040434360504, 0.4615879952907562, 0.3633270859718323, 0.3486518859863281, 0.4209037125110626, 0.318261057138443, 0.32238349318504333, 0.3470683693885803, 0.2956037223339081, 0.3924330770969391, 0.3243030905723572, 0.519384503364563, 0.34880802035331726, 0.39669159054756165, 0.5521753430366516, 0.391692578792572, 0.3037213683128357, 0.3335234820842743, 0.35175979137420654, 0.4810446500778198, 0.3629048764705658, 0.38243141770362854, 0.33281272649765015, 0.4119153916835785, 0.3629534840583801, 0.3527759313583374, 0.35738444328308105, 0.27999091148376465, 0.4121237099170685, 0.3548033833503723, 0.4882602095603943, 0.3487224578857422, 0.4093340337276459, 0.26009100675582886, 0.4162060618400574, 0.45504653453826904, 0.44184961915016174, 0.44364264607429504, 0.28177425265312195, 0.3868492841720581, 0.34795549511909485, 0.3837064206600189, 0.36904484033584595, 0.3688608705997467, 0.3023652136325836, 0.5267637372016907, 0.2763509750366211, 0.380108505487442, 0.47341829538345337, 0.3595220446586609, 0.4254806339740753, 0.3077811896800995, 0.4193083345890045, 0.5202822089195251, 0.35006940364837646, 0.36460238695144653, 0.3676091730594635, 0.41639313101768494, 0.3063492774963379, 0.24775083363056183]
Val loss  1.679545283317566
Epoch 5/5

  0%|          | 0/324 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

Train loss  [0.2888123691082001, 0.2609193027019501, 0.2513764798641205, 0.28204935789108276, 0.2758316993713379, 0.20054160058498383, 0.30133283138275146, 0.23529498279094696, 0.32541805505752563, 0.3728162348270416, 0.24444904923439026, 0.2843824326992035, 0.30237895250320435, 0.2139168083667755, 0.19181330502033234, 0.31469008326530457, 0.15198688209056854, 0.2562277317047119, 0.21104398369789124, 0.2909272015094757, 0.27627259492874146, 0.26083672046661377, 0.18386709690093994, 0.3705122768878937, 0.152248352766037, 0.3349694609642029, 0.2508477568626404, 0.22886697947978973, 0.3743365705013275, 0.3493349552154541, 0.3577320873737335, 0.23790450394153595, 0.30650344491004944, 0.36145520210266113, 0.22603917121887207, 0.26569297909736633, 0.178852379322052, 0.1738128662109375, 0.28645017743110657, 0.33052095770835876, 0.27616140246391296, 0.32162952423095703, 0.22855816781520844, 0.23171420395374298, 0.2665656507015228, 0.24569280445575714, 0.2816125452518463, 0.19548673927783966, 0.25385528802871704, 0.30360400676727295, 0.1888372302055359, 0.30126410722732544, 0.2154083549976349, 0.2679884135723114, 0.19501373171806335, 0.31048375368118286, 0.25220566987991333, 0.37024638056755066, 0.28249484300613403, 0.19474081695079803, 0.2686798572540283, 0.1668487787246704, 0.27051544189453125, 0.202323317527771, 0.24320204555988312, 0.323501855134964, 0.24419201910495758, 0.21778665482997894, 0.248902827501297, 0.29154670238494873, 0.21120606362819672, 0.15904562175273895, 0.3158860206604004, 0.2830960750579834, 0.2598087787628174, 0.36903056502342224, 0.34507817029953003, 0.2461359202861786, 0.2187432497739792, 0.25560134649276733, 0.3303500711917877, 0.2600399851799011, 0.21374130249023438, 0.2112230509519577, 0.2579379975795746, 0.27533361315727234, 0.21246318519115448, 0.2575027644634247, 0.34520092606544495, 0.18536493182182312, 0.2449122667312622, 0.3003580570220947, 0.1914079338312149, 0.3588124215602875, 0.33560678362846375, 0.15260908007621765, 0.41828516125679016, 0.28700631856918335, 0.24629628658294678, 0.1983208805322647, 0.34753283858299255, 0.3398743271827698, 0.2935347259044647, 0.24424608051776886, 0.2859780192375183, 0.2793177366256714, 0.31090739369392395, 0.40762826800346375, 0.23540961742401123, 0.260240375995636, 0.27768778800964355, 0.21620775759220123, 0.45913365483283997, 0.25891125202178955, 0.26994451880455017, 0.23633144795894623, 0.2941730320453644, 0.2997995615005493, 0.3656311333179474, 0.2584854066371918, 0.20436985790729523, 0.2642974853515625, 0.38572028279304504, 0.2903064787387848, 0.32629674673080444, 0.3432276248931885, 0.4878489375114441, 0.3324214220046997, 0.2386000156402588, 0.1874503195285797, 0.28486916422843933, 0.270434707403183, 0.2492208480834961, 0.2738253176212311, 0.30777838826179504, 0.3486892879009247, 0.22592411935329437, 0.1580793559551239, 0.4455227255821228, 0.2845802307128906, 0.31005948781967163, 0.26833829283714294, 0.3228781521320343, 0.2623337209224701, 0.2622334361076355, 0.2372414618730545, 0.32624244689941406, 0.17566384375095367, 0.2906018793582916, 0.3539917469024658, 0.3048706352710724, 0.3647109866142273, 0.34771084785461426, 0.3238529860973358, 0.30382412672042847, 0.3498114347457886, 0.22329306602478027, 0.188724085688591, 0.18735472857952118, 0.26081717014312744, 0.3496565520763397, 0.24154934287071228, 0.391372948884964, 0.28565338253974915, 0.31402909755706787, 0.2851582169532776, 0.38995110988616943, 0.26665884256362915, 0.36608806252479553, 0.29314449429512024, 0.29157885909080505, 0.2414219081401825, 0.35499441623687744, 0.285916805267334, 0.2554526925086975, 0.2723113000392914, 0.37861427664756775, 0.35467204451560974, 0.2766028046607971, 0.4010547399520874, 0.2955699563026428, 0.2465873658657074, 0.3562302589416504, 0.2833331227302551, 0.24292366206645966, 0.40372779965400696, 0.2893937826156616, 0.3806731700897217, 0.2195737063884735, 0.3500014543533325, 0.3784087896347046, 0.3023207187652588, 0.2639564275741577, 0.2405838817358017, 0.2049490362405777, 0.30218005180358887, 0.3551921546459198, 0.42261332273483276, 0.42690178751945496, 0.32008111476898193, 0.33016180992126465, 0.2729227840900421, 0.357092022895813, 0.3708139955997467, 0.3514202833175659, 0.2165631651878357, 0.1381470113992691, 0.31920644640922546, 0.40246713161468506, 0.4603390097618103, 0.38714599609375, 0.20969052612781525, 0.20232956111431122, 0.34899604320526123, 0.35129085183143616, 0.2254972606897354, 0.28784415125846863, 0.29532450437545776, 0.2960018217563629, 0.3598136901855469, 0.30642467737197876, 0.3908687233924866, 0.2828144431114197, 0.3294851779937744, 0.31467705965042114, 0.24789363145828247, 0.33509981632232666, 0.44747593998908997, 0.2824585437774658, 0.3295632004737854, 0.43597283959388733, 0.36736562848091125, 0.24051417410373688, 0.288833349943161, 0.2573414444923401, 0.31739673018455505, 0.343740314245224, 0.332996666431427, 0.36132127046585083, 0.37462493777275085, 0.30436182022094727, 0.40395587682724, 0.27010977268218994, 0.2716098725795746, 0.2282869517803192, 0.294619619846344, 0.33643218874931335, 0.30248957872390747, 0.2567622661590576, 0.34214773774147034, 0.34418627619743347, 0.3074886202812195, 0.2823716700077057, 0.4907173812389374, 0.4578798711299896, 0.329708993434906, 0.4188709855079651, 0.3395095765590668, 0.3319033980369568, 0.27945294976234436, 0.37063291668891907, 0.3781901001930237, 0.3075471818447113, 0.45581090450286865, 0.3123086392879486, 0.31309184432029724, 0.2991948425769806, 0.3861214816570282, 0.4097692668437958, 0.286841481924057, 0.27347078919410706, 0.24698323011398315, 0.37359336018562317, 0.328158438205719, 0.41552338004112244, 0.2366403043270111, 0.4336186349391937, 0.2987382709980011, 0.2857908606529236, 0.3507593870162964, 0.41042789816856384, 0.40161606669425964, 0.46958979964256287, 0.4307106137275696, 0.30394673347473145, 0.3313598036766052, 0.3798481523990631, 0.2968917787075043, 0.32378989458084106, 0.3448562026023865, 0.2869071662425995, 0.3703744113445282, 0.2802797555923462, 0.3387022018432617, 0.22274264693260193, 0.3870428800582886, 0.3031388521194458, 0.3641253411769867, 0.38291501998901367, 0.3309776484966278, 0.31738436222076416, 0.3685240149497986, 0.28018563985824585, 0.40382975339889526, 0.4091757535934448, 0.24117349088191986, 0.2881304621696472, 0.2728578448295593, 0.2682051658630371, 0.384735107421875, 0.31716763973236084, 0.23138800263404846, 0.3826419413089752, 0.36735981702804565, 0.45668530464172363, 0.3350934386253357, 0.29435989260673523, 0.4344099164009094, 0.44459137320518494, 0.3024233281612396, 0.31829017400741577, 0.2757088840007782, 0.30480945110321045, 0.17948810756206512]
Val loss  1.9164053201675415

RecurrentClassifier(
  (embeddings): Embedding(29023, 300, padding_idx=0)
  (cell): LSTM(300, 128, num_layers=2, batch_first=True, dropout=0.2, bidirectional=True)
  (out_dropout): Dropout(p=0.2, inplace=False)
  (out_proj): Sequential(
    (0): Linear(in_features=512, out_features=200, bias=True)
    (1): Linear(in_features=200, out_features=6, bias=True)
  )
)

# Save Model

In [ ]:
t.save("baseline_model.ckpt")

# Load pretrained Model

In [ ]:
t = Trainer.load("baseline_model.ckpt")

# Define predict function

In [ ]:
def predict(model, text):
    tok_text = tok.tokenize(text)
    indexed_text = torch.tensor(vocab.vectorize(tok_text)).to(t.device)
    genre = model(pack_sequence([indexed_text])).argmax().item()
    return genre

In [50]:
valid_predictions = t.predict(val_dataloader)
print(classification_report(val_labels, valid_predictions))

NameError: name 'classification_report' is not defined

# Get testset predictions

In [ ]:
test['text'] = test['text'].apply(
    lambda x: ' '.join(
        token.lemma_.lower() for token in nlp(x) if
        not token.is_stop
        and not token.is_punct
        and not token.is_digit
        and not token.like_email
        and not token.like_num
        and not token.is_space
    )
)

In [ ]:
test_dataloader = DataLoader(TextDataset([tok.tokenize(t) for t in test.text.values], [-1] * test.shape[0], vocab),
                             batch_size=trainer_config["batch_size"],
                             shuffle=False,
                             num_workers=0,
                             collate_fn=val_dataset.collate_fn)

predictions = t.predict(test_dataloader)

# Create submission

In [ ]:
sample_submission = pd.read_csv(os.path.join(path, "sample_submission.csv"))
sample_submission["rate"] = predictions
sample_submission.rate = le.inverse_transform(sample_submission.rate)
sample_submission.head()

In [ ]:
sample_submission.to_csv("submission.csv", index=False)